/* ============================================================================
   squads.js — full projected World Cup 2026 squads for all 24 contenders.
   Format: [shirtNo, "Name", "POS", "Club", tier?]
   The FIRST 11 players of each list are the projected starting XI (used for the
   pitch); the remainder are bench / squad depth. ~24–26 players per nation.
   All affiliations are illustrative (≈2025/26). Exposes window.WC_SQUADS.
   ========================================================================== */
window.WC_SQUADS = {
  ESP: ["4-3-3", [
    [1,"Unai Simón","GK","Athletic Club"],[2,"D. Carvajal","RB","Real Madrid"],[4,"R. Le Normand","CB","Atlético Madrid"],[14,"A. Laporte","CB","Al-Nassr"],[24,"M. Cucurella","LB","Chelsea"],[16,"Rodri","CDM","Manchester City",1.1],[8,"Pedri","CM","Barcelona",1.1],[12,"F. Ruiz","CM","Paris SG"],[19,"L. Yamal","RW","Barcelona",1.5],[7,"Á. Morata","ST","AC Milan",1.3],[17,"N. Williams","LW","Athletic Club",1.3],
    [23,"D. Raya","GK","Arsenal"],[13,"R. Sánchez","GK","Paris SG"],[5,"D. Vivian","CB","Athletic Club"],[3,"P. Cubarsí","CB","Barcelona"],[22,"J. Navas","RB","Sevilla"],[18,"A. Grimaldo","LB","Bayer Leverkusen"],[6,"M. Merino","CM","Arsenal"],[26,"F. López","CM","Barcelona"],[10,"D. Olmo","CAM","Barcelona",1.2],[11,"F. Torres","ST","Barcelona",1.1],[9,"J. Joselu","ST","Al-Gharafa"],[21,"M. Oyarzabal","ST","Real Sociedad",1.1],[20,"P. Sarabia","RW","Wolves"],[15,"A. Fernández","CB","Real Betis"],
  ]],
  FRA: ["4-3-3", [
    [1,"M. Maignan","GK","AC Milan"],[5,"J. Koundé","RB","Barcelona"],[17,"W. Saliba","CB","Arsenal",1.1],[4,"D. Upamecano","CB","Bayern Munich"],[22,"T. Hernández","LB","AC Milan"],[8,"A. Tchouaméni","CDM","Real Madrid"],[6,"E. Camavinga","CM","Real Madrid"],[7,"A. Griezmann","CAM","Atlético Madrid",1.2],[11,"O. Dembélé","RW","Paris SG",1.2],[10,"K. Mbappé","ST","Real Madrid",1.6],[20,"B. Barcola","LW","Paris SG",1.1],
    [16,"B. Samba","GK","Rennes"],[23,"A. Areola","GK","West Ham"],[2,"J. Clauss","RB","Nice"],[3,"F. Mendy","LB","Real Madrid"],[15,"I. Konaté","CB","Liverpool"],[24,"L. Hernández","CB","Paris SG"],[14,"A. Rabiot","CM","Marseille"],[13,"N. Kanté","CDM","Al-Ittihad"],[12,"W. Zaïre-Emery","CM","Paris SG"],[9,"O. Giroud","ST","Lille",1.1],[18,"R. Kolo Muani","ST","Juventus",1.1],[26,"M. Thuram","ST","Inter",1.2],[21,"K. Coman","RW","Bayern Munich",1.1],
  ]],
  BRA: ["4-3-3", [
    [1,"Alisson","GK","Liverpool"],[2,"Danilo","RB","Flamengo"],[4,"Marquinhos","CB","Paris SG"],[3,"G. Magalhães","CB","Arsenal"],[6,"Wendell","LB","FC Porto"],[5,"André","CDM","Wolves"],[17,"B. Guimarães","CM","Newcastle"],[10,"L. Paquetá","CAM","West Ham",1.1],[11,"Rodrygo","RW","Real Madrid",1.2],[9,"Endrick","ST","Real Madrid",1.1],[20,"Vinícius Jr","LW","Real Madrid",1.5],
    [12,"Bento","GK","Al-Nassr"],[23,"Ederson","GK","Manchester City"],[13,"Yan Couto","RB","Borussia Dortmund"],[14,"É. Militão","CB","Real Madrid"],[15,"Beraldo","CB","Paris SG"],[16,"Abner","LB","Lyon"],[8,"Bruno Guimarães","CM","Newcastle"],[18,"Andreas Pereira","CM","Fulham"],[7,"Savinho","RW","Manchester City",1.1],[19,"Raphinha","LW","Barcelona",1.3],[21,"Gabriel Martinelli","LW","Arsenal",1.1],[22,"Igor Jesus","ST","Botafogo"],[25,"João Pedro","ST","Chelsea",1.1],
  ]],
  ARG: ["4-3-3", [
    [23,"E. Martínez","GK","Aston Villa"],[26,"N. Molina","RB","Atlético Madrid"],[13,"C. Romero","CB","Tottenham",1.1],[19,"N. Otamendi","CB","Benfica"],[3,"N. Tagliafico","LB","Lyon"],[7,"R. De Paul","CM","Atlético Madrid"],[20,"A. Mac Allister","CM","Liverpool",1.1],[24,"E. Fernández","CM","Chelsea"],[10,"L. Messi","RW","Inter Miami",1.6],[9,"J. Álvarez","ST","Atlético Madrid",1.3],[15,"N. González","LW","Juventus",1.1],
    [1,"F. Armani","GK","River Plate"],[12,"G. Rulli","GK","Marseille"],[2,"G. Montiel","RB","Sevilla"],[6,"G. Pezzella","CB","River Plate"],[25,"L. Balerdi","CB","Marseille"],[8,"M. Acuña","LB","River Plate"],[5,"L. Paredes","CDM","Boca Juniors"],[18,"G. Lo Celso","CM","Real Betis"],[11,"Á. Di María","RW","Benfica",1.1],[22,"L. Martínez","ST","Inter",1.3],[16,"T. Almada","CAM","Atlético Madrid",1.1],[21,"P. Dybala","CAM","Roma",1.1],[17,"A. Garnacho","LW","Chelsea",1.1],
  ]],
  ENG: ["4-2-3-1", [
    [1,"J. Pickford","GK","Everton"],[2,"K. Walker","RB","Burnley"],[5,"J. Stones","CB","Manchester City"],[6,"M. Guéhi","CB","Crystal Palace"],[3,"L. Shaw","LB","Manchester Utd"],[4,"D. Rice","CDM","Arsenal"],[26,"K. Mainoo","CM","Manchester Utd"],[7,"B. Saka","RW","Arsenal",1.3],[10,"J. Bellingham","CAM","Real Madrid",1.4],[11,"P. Foden","LW","Manchester City",1.2],[9,"H. Kane","ST","Bayern Munich",1.4],
    [13,"D. Henderson","GK","Brentford"],[23,"J. Pope","GK","Newcastle"],[12,"K. Trippier","LB","Newcastle"],[14,"E. Konsa","CB","Aston Villa"],[15,"L. Colwill","CB","Chelsea"],[2,"T. Livramento","RB","Newcastle"],[8,"A. Wharton","CM","Crystal Palace"],[16,"C. Gallagher","CM","Atlético Madrid"],[20,"C. Palmer","CAM","Chelsea",1.3],[17,"J. Gordon","LW","Newcastle",1.1],[19,"O. Watkins","ST","Aston Villa",1.2],[24,"M. Rashford","LW","Aston Villa",1.1],[21,"E. Eze","CAM","Arsenal",1.1],
  ]],
  GER: ["4-2-3-1", [
    [1,"M. Neuer","GK","Bayern Munich"],[6,"J. Kimmich","RB","Bayern Munich"],[4,"J. Tah","CB","Bayern Munich"],[2,"A. Rüdiger","CB","Real Madrid",1.1],[18,"M. Mittelstädt","LB","VfB Stuttgart"],[23,"R. Andrich","CDM","Bayer Leverkusen"],[15,"A. Pavlović","CM","Bayern Munich"],[19,"L. Sané","RW","Galatasaray",1.1],[10,"J. Musiala","CAM","Bayern Munich",1.4],[17,"F. Wirtz","LW","Liverpool",1.3],[7,"K. Havertz","ST","Arsenal",1.1],
    [12,"O. Baumann","GK","Hoffenheim"],[22,"A. Nübel","GK","VfB Stuttgart"],[3,"D. Raum","LB","RB Leipzig"],[5,"N. Schlotterbeck","CB","Borussia Dortmund"],[24,"R. Koch","CB","Eintracht Frankfurt"],[16,"W. Anton","CB","Borussia Dortmund"],[8,"L. Goretzka","CM","Bayern Munich"],[14,"R. Gündoğan","CM","Manchester City",1.1],[21,"A. Groß","CM","Borussia Dortmund"],[9,"N. Füllkrug","ST","West Ham",1.2],[26,"D. Undav","ST","VfB Stuttgart",1.1],[11,"K. Adeyemi","RW","Borussia Dortmund",1.1],[20,"J. Brandt","CAM","Borussia Dortmund"],
  ]],
  POR: ["4-3-3", [
    [22,"D. Costa","GK","FC Porto"],[20,"J. Cancelo","RB","Al-Hilal"],[4,"R. Dias","CB","Manchester City",1.1],[24,"A. Inácio","CB","Sporting CP"],[19,"N. Mendes","LB","Paris SG"],[6,"J. Palhinha","CDM","Bayern Munich"],[16,"Vitinha","CM","Paris SG"],[8,"B. Fernandes","CAM","Manchester Utd",1.2],[11,"B. Silva","RW","Manchester City",1.2],[7,"C. Ronaldo","ST","Al-Nassr",1.4],[15,"R. Leão","LW","AC Milan",1.3],
    [1,"R. Patrício","GK","free agent"],[12,"J. Sá","GK","Wolves"],[2,"N. Semedo","RB","Wolves"],[3,"Pepe","CB","FC Porto"],[5,"Nuno Mendes","LB","Paris SG"],[13,"D. Carvalho","CB","Benfica"],[14,"G. Inácio","CB","Sporting CP"],[18,"R. Neves","CDM","Al-Hilal"],[10,"B. Fernandes","CM","Manchester Utd"],[23,"V. Ferreira","CM","FC Porto"],[9,"G. Ramos","ST","Paris SG",1.2],[26,"P. Neto","RW","Chelsea",1.1],[17,"F. Conceição","RW","Juventus",1.1],[21,"D. Jota","ST","Liverpool",1.2],
  ]],
  NED: ["4-3-3", [
    [1,"B. Verbruggen","GK","Brighton"],[22,"D. Dumfries","RB","Inter"],[4,"M. de Ligt","CB","Manchester Utd"],[6,"V. van Dijk","CB","Liverpool",1.1],[5,"N. Aké","LB","Manchester City"],[15,"J. Schouten","CDM","PSV"],[21,"F. de Jong","CM","Barcelona",1.2],[14,"T. Reijnders","CM","Manchester City"],[18,"D. Malen","RW","Aston Villa"],[10,"M. Depay","ST","Corinthians",1.2],[11,"C. Gakpo","LW","Liverpool",1.2],
    [23,"M. Flekken","GK","Bayer Leverkusen"],[13,"N. Bijlow","GK","Feyenoord"],[2,"J. Geertruida","RB","RB Leipzig"],[3,"M. de Vrij","CB","Inter"],[17,"D. Dumfries","RB","Inter"],[12,"I. Hartman","LB","Feyenoord"],[20,"T. Koopmeiners","CM","Juventus",1.1],[8,"M. Wieffer","CM","Brighton"],[24,"X. Simons","CAM","RB Leipzig",1.2],[7,"X. Simons","RW","RB Leipzig"],[9,"W. Weghorst","ST","Ajax",1.1],[19,"B. Brobbey","ST","Ajax",1.1],[26,"E. Maatsen","LB","Aston Villa"],
  ]],
  BEL: ["3-4-2-1", [
    [1,"K. Casteels","GK","Al-Qadsiah"],[2,"Z. Debast","CB","Sporting CP"],[5,"J. Vertonghen","CB","Anderlecht"],[3,"A. Theate","CB","Eintracht Frankfurt"],[15,"T. Castagne","RWB","Fulham"],[6,"A. Onana","CM","Aston Villa"],[8,"Y. Tielemans","CM","Aston Villa",1.1],[21,"M. De Cuyper","LWB","Brighton"],[7,"K. De Bruyne","CAM","Napoli",1.3],[10,"L. Trossard","CAM","Arsenal",1.2],[9,"R. Lukaku","ST","Napoli",1.3],
    [12,"M. Sels","GK","Nottingham Forest"],[13,"T. Kaminski","GK","Metz"],[4,"W. Faes","CB","Leicester City"],[24,"K. Sardella","RWB","Anderlecht"],[18,"O. Mangala","CM","Lyon"],[20,"M. Mangala","CM","Everton"],[25,"N. Raskin","CM","Rangers"],[11,"C. Doku","RW","Manchester City",1.2],[22,"J. Bakayoko","RW","PSV",1.1],[17,"D. Openda","ST","RB Leipzig",1.2],[19,"R. Lukebakio","RW","Sevilla",1.1],[14,"D. Vanaken","CM","Club Brugge"],
  ]],
  CRO: ["4-3-3", [
    [1,"D. Livaković","GK","Fenerbahçe"],[2,"J. Stanišić","RB","Bayer Leverkusen"],[5,"M. Erlić","CB","Sassuolo"],[20,"J. Gvardiol","CB","Manchester City",1.2],[19,"B. Sosa","LB","Ajax"],[10,"L. Modrić","CM","AC Milan",1.2],[8,"M. Kovačić","CM","Manchester City"],[26,"L. Sučić","CAM","RB Salzburg"],[11,"M. Baturina","RW","RB Leipzig"],[9,"A. Kramarić","ST","Hoffenheim",1.1],[4,"I. Perišić","LW","Hajduk Split",1.1],
    [12,"I. Nevistić","GK","Dinamo Zagreb"],[23,"D. Labrović","GK","Rijeka"],[3,"M. Pongračić","CB","Fiorentina"],[6,"J. Šutalo","CB","Ajax"],[22,"J. Juranović","RB","Union Berlin"],[18,"M. Pjaca","LW","Rijeka"],[7,"L. Majer","CM","Wolves"],[15,"M. Pašalić","CAM","Atalanta",1.1],[14,"I. Sunjić","CDM","Spartak Moscow"],[17,"A. Budimir","ST","Osasuna",1.1],[16,"M. Petković","ST","Dinamo Zagreb"],[13,"N. Moro","CM","Hajduk Split"],
  ]],
  URU: ["4-3-3", [
    [23,"S. Rochet","GK","Inter Miami"],[2,"N. Nández","RB","Al-Qadsiah"],[19,"S. Coates","CB","Sporting CP"],[3,"R. Araújo","CB","Barcelona",1.1],[4,"M. Olivera","LB","Napoli"],[6,"R. Bentancur","CM","Tottenham"],[15,"F. Valverde","CM","Real Madrid",1.3],[5,"M. Ugarte","CDM","Manchester Utd"],[11,"F. Pellistri","RW","Panathinaikos"],[9,"D. Núñez","ST","Liverpool",1.2],[7,"N. de la Cruz","LW","Flamengo",1.1],
    [1,"F. Muslera","GK","Galatasaray"],[12,"R. Mejía","GK","Liga de Quito"],[17,"M. Viña","LB","Flamengo"],[22,"R. Cáceres","CB","free agent"],[13,"G. Varela","RB","Flamengo"],[8,"N. Fonseca","CM","River Plate"],[14,"L. Sanabria","CM","Talleres"],[10,"G. de Arrascaeta","CAM","Flamengo",1.2],[20,"M. Araújo","RW","Juventus"],[21,"E. Cavani","ST","Boca Juniors",1.1],[18,"M. Satriano","ST","Lens",1.1],
  ]],
  USA: ["4-3-3", [
    [1,"M. Turner","GK","New England"],[2,"S. Dest","RB","PSV"],[3,"C. Richards","CB","Crystal Palace"],[12,"M. Robinson","CB","Toronto FC"],[5,"A. Robinson","LB","Fulham"],[4,"T. Adams","CDM","Bournemouth"],[8,"W. McKennie","CM","Juventus"],[6,"Y. Musah","CM","Atalanta"],[10,"C. Pulisic","RW","AC Milan",1.3],[9,"F. Balogun","ST","AS Monaco",1.1],[21,"T. Weah","LW","Juventus"],
    [13,"M. Freese","GK","NYCFC"],[18,"P. Schulte","GK","St. Louis City"],[22,"J. Scally","RB","M'gladbach"],[15,"C. Carter-Vickers","CB","Celtic"],[20,"T. Ream","CB","Charlotte FC"],[14,"L. de la Torre","CM","San Diego"],[16,"J. Cardoso","CDM","Real Betis"],[24,"G. Reyna","CAM","Borussia Dortmund",1.1],[11,"B. Aaronson","RW","Leeds Utd"],[7,"T. Tillman","CAM","Bayer Leverkusen"],[19,"H. Wright","ST","Coventry City"],[17,"M. Sargent","ST","Norwich City",1.1],
  ]],
  COL: ["4-3-3", [
    [1,"C. Vargas","GK","Atlético Mineiro"],[4,"S. Arias","RB","Fortaleza"],[2,"D. Sánchez","CB","Galatasaray"],[3,"J. Lucumí","CB","Bologna"],[17,"J. Mojica","LB","Cagliari"],[5,"K. Castaño","CDM","Lazio"],[16,"J. Lerma","CM","Crystal Palace"],[10,"J. Rodríguez","CAM","León",1.2],[11,"J. Cuadrado","RW","Pescara"],[9,"J. Córdoba","ST","Krasnodar",1.1],[7,"L. Díaz","LW","Bayern Munich",1.3],
    [12,"C. Montero","GK","Vélez"],[22,"D. Ospina","GK","Atlético Nacional"],[13,"Y. Mina","CB","Cagliari"],[6,"W. Tesillo","CB","León"],[23,"D. Muñoz","RB","Crystal Palace"],[8,"R. Ríos","CM","Benfica"],[15,"M. Uribe","CM","Atlético Nacional"],[14,"L. Sinisterra","RW","Bournemouth",1.1],[21,"D. Arias","RW","Atlético Nacional"],[19,"R. Borré","ST","Internacional",1.1],[18,"J. Borja","ST","River Plate"],
  ]],
  ITA: ["3-5-2", [
    [1,"G. Donnarumma","GK","Manchester City"],[3,"A. Bastoni","CB","Inter"],[23,"A. Buongiorno","CB","Napoli"],[15,"G. Mancini","CB","Roma"],[2,"G. Di Lorenzo","RWB","Napoli"],[18,"N. Barella","CM","Inter",1.1],[8,"S. Tonali","CM","Newcastle"],[10,"L. Pellegrini","CAM","Roma",1.1],[13,"F. Dimarco","LWB","Inter"],[9,"M. Retegui","ST","Al-Qadsiah",1.2],[14,"M. Kean","ST","Fiorentina",1.1],
    [12,"M. Vicario","GK","Tottenham"],[22,"G. Vicario","GK","Tottenham"],[4,"A. Cambiaso","RWB","Juventus"],[5,"R. Calafiori","CB","Arsenal"],[6,"G. Scalvini","CB","Atalanta"],[16,"D. Frattesi","CM","Inter",1.1],[7,"D. Frattesi","CM","Inter"],[20,"G. Raspadori","ST","Napoli",1.1],[11,"G. Scamacca","ST","Atalanta",1.1],[17,"M. Zaccagni","LW","Lazio",1.1],[21,"N. Fagioli","CM","Fiorentina"],[19,"W. N'Dicka","CB","Roma"],
  ]],
  SUI: ["4-2-3-1", [
    [1,"Y. Sommer","GK","Inter"],[2,"S. Widmer","RB","Mainz"],[5,"M. Akanji","CB","Manchester City",1.1],[22,"F. Schär","CB","Newcastle"],[13,"R. Rodríguez","LB","Real Betis"],[10,"G. Xhaka","CDM","Bayer Leverkusen",1.1],[8,"R. Freuler","CM","Bologna"],[23,"X. Shaqiri","RW","FC Basel",1.1],[15,"D. Zakaria","CAM","AS Monaco"],[17,"R. Vargas","LW","AS Monaco",1.1],[9,"B. Embolo","ST","AS Monaco",1.2],
    [12,"G. Mvogo","GK","Lorient"],[21,"P. Köhn","GK","AS Monaco"],[3,"S. Lotomba","RB","Nice"],[4,"N. Elvedi","CB","M'gladbach"],[20,"E. Comert","CB","Spezia"],[6,"D. Sow","CM","Nottingham Forest"],[16,"V. Sierro","CM","Toulouse"],[14,"M. Aebischer","CM","Bologna"],[7,"B. Mehmedi","RW","Antalyaspor"],[18,"K. Itten","ST","Grasshopper"],[11,"Z. Amdouni","ST","Burnley",1.1],[19,"D. Ndoye","RW","Bologna",1.1],
  ]],
  DEN: ["4-3-3", [
    [1,"K. Schmeichel","GK","Celtic"],[2,"A. Bah","RB","Benfica"],[6,"A. Christensen","CB","Barcelona"],[3,"J. Vestergaard","CB","Leicester City"],[5,"J. Maehle","LB","Wolfsburg"],[23,"P. Højbjerg","CDM","Marseille"],[7,"M. Hjulmand","CM","Sporting CP"],[10,"C. Eriksen","CAM","Manchester Utd",1.2],[8,"M. Damsgaard","RW","Brentford"],[9,"R. Højlund","ST","Napoli",1.2],[17,"G. Isaksen","LW","Lazio"],
    [16,"M. Ronnow","GK","Union Berlin"],[22,"O. Christensen","GK","Hertha Berlin"],[4,"J. Andersen","CB","Crystal Palace"],[13,"R. Kristensen","RB","Eintracht Frankfurt"],[14,"M. Wind","ST","Wolfsburg",1.1],[15,"C. Norgaard","CDM","Arsenal"],[19,"J. Lindstrom","CAM","Everton",1.1],[20,"Y. Poulsen","ST","RB Leipzig",1.1],[11,"A. Skov Olsen","RW","Club Brugge",1.1],[18,"M. Frese","RB","Hoffenheim"],[21,"M. Dorgu","LB","Manchester Utd"],
  ]],
  MEX: ["4-3-3", [
    [1,"L. Malagón","GK","Club América"],[19,"J. Vásquez","RB","Genoa"],[3,"C. Montes","CB","Monterrey"],[5,"J. Sánchez","CB","Cruz Azul"],[23,"J. Gallardo","LB","Tigres"],[4,"E. Álvarez","CDM","West Ham",1.1],[14,"L. Chávez","CM","Bournemouth"],[18,"L. Romo","CM","Monterrey"],[22,"H. Lozano","RW","San Diego",1.2],[11,"S. Giménez","ST","AC Milan",1.2],[7,"U. Antuna","LW","Cruz Azul"],
    [12,"R. Acevedo","GK","Cruz Azul"],[13,"C. Acevedo","GK","Santos Laguna"],[2,"K. Álvarez","RB","Feyenoord"],[15,"I. Vázquez","CB","Toluca"],[20,"H. Sánchez","CB","Cruz Azul"],[6,"G. Sepúlveda","CDM","Guadalajara"],[8,"C. Rodríguez","CM","Club América"],[16,"H. Herrera","CM","Houston Dynamo"],[10,"A. Vega","CAM","Guadalajara",1.1],[9,"R. Jiménez","ST","Fulham",1.2],[21,"H. Lozano","RW","San Diego"],[17,"O. Pineda","RW","AZ Alkmaar"],
  ]],
  MAR: ["4-3-3", [
    [1,"Y. Bounou","GK","Al-Hilal"],[2,"A. Hakimi","RB","Paris SG",1.2],[6,"N. Aguerd","CB","West Ham"],[5,"R. Saïss","CB","Al-Shabab"],[3,"N. Mazraoui","LB","Manchester Utd"],[4,"S. Amrabat","CDM","Fenerbahçe"],[8,"A. Ounahi","CM","Panathinaikos"],[11,"S. Amallah","CM","Standard Liège"],[7,"H. Ziyech","RW","Al-Duhail",1.1],[19,"Y. En-Nesyri","ST","Fenerbahçe",1.1],[9,"S. Boufal","LW","Al-Rayyan"],
    [12,"M. Aithamou","GK","Le Havre"],[22,"A. Tagnaouti","GK","RS Berkane"],[18,"A. Hakimi","RB","Paris SG"],[20,"A. Masina","LB","Lecce"],[24,"J. El Yamiq","CB","Real Valladolid"],[14,"Z. Aboukhlal","RW","Toulouse",1.1],[15,"S. Ezzalzouli","LW","Real Betis",1.1],[17,"S. Ounahi","CM","Marseille"],[10,"A. Harit","CAM","Marseille",1.1],[21,"W. Cheddira","ST","Espanyol"],[16,"A. El Khannouss","CAM","Leicester City",1.1],
  ]],
  JPN: ["4-2-3-1", [
    [1,"D. Schmidt","GK","Sint-Truiden"],[2,"Y. Sugawara","RB","Southampton"],[22,"K. Itakura","CB","Ajax"],[16,"T. Tomiyasu","CB","Arsenal",1.1],[3,"H. Itō","LB","Bayern Munich"],[6,"W. Endō","CDM","Liverpool"],[7,"H. Morita","CM","Sporting CP"],[20,"T. Kubo","RW","Real Sociedad",1.2],[15,"D. Kamada","CAM","Crystal Palace"],[14,"K. Mitoma","LW","Brighton",1.2],[19,"A. Ueda","ST","Feyenoord",1.1],
    [12,"K. Osako","GK","Sanfrecce Hiroshima"],[23,"Z. Suzuki","GK","Parma"],[4,"K. Taniguchi","CB","Sint-Truiden"],[5,"Y. Itakura","CB","Ajax"],[26,"H. Sakai","RB","Urawa Reds"],[8,"R. Doan","RW","Freiburg",1.1],[10,"T. Minamino","CAM","AS Monaco",1.1],[13,"H. Morishita","CM","Sanfrecce Hiroshima"],[17,"A. Tanaka","CM","Leeds Utd"],[9,"K. Ueda","ST","Feyenoord"],[11,"K. Furuhashi","ST","Birmingham City",1.1],[18,"T. Asano","ST","Partizan"],
  ]],
  SEN: ["4-3-3", [
    [1,"É. Mendy","GK","Al-Ahli"],[21,"Y. Sabaly","RB","Real Betis"],[3,"K. Koulibaly","CB","Al-Hilal",1.1],[22,"A. Diallo","CB","Al-Arabi"],[12,"F. Jakobs","LB","Galatasaray"],[5,"P. Gueye","CDM","Villarreal"],[17,"P. M. Sarr","CM","Tottenham"],[6,"N. Mendy","CM","Al-Ahli"],[18,"I. Sarr","RW","Crystal Palace",1.1],[9,"N. Jackson","ST","Bayern Munich",1.2],[10,"S. Mané","LW","Al-Nassr",1.3],
    [16,"M. Diaw","GK","RS Berkane"],[23,"S. Dieng","GK","Le Havre"],[2,"K. Mbaye","RB","Bologna"],[4,"M. Niakhaté","CB","Lyon"],[13,"I. Jakobs","LB","Galatasaray"],[8,"L. Camara","CM","RB Salzburg"],[15,"K. Kouyaté","CDM","Steaua"],[14,"I. Gueye","CM","Everton"],[7,"S. Sarr","RW","Standard Liège"],[19,"F. Balde","ST","Celta Vigo",1.1],[11,"H. Diallo","ST","Al-Ettifaq",1.1],[20,"B. Dia","ST","Lazio",1.1],
  ]],
  KOR: ["4-2-3-1", [
    [1,"S. Kim","GK","Jeonbuk"],[2,"Y. Kim","RB","Mainz"],[4,"M. Kim","CB","Bayern Munich",1.1],[20,"J. Kwon","CB","Hellas Verona"],[12,"J. Lee","LB","Paris SG",1.1],[6,"I. Hwang","CDM","Genoa"],[15,"J. Park","CM","Jeonbuk"],[7,"H. Son","RW","LAFC",1.3],[10,"K. Lee","CAM","Bayern Munich",1.2],[11,"C. Hwang","LW","Wolves",1.1],[9,"G. Cho","ST","Norwich City",1.1],
    [21,"B. Jo","GK","Ulsan"],[23,"H. Song","GK","Jeonbuk"],[3,"Y. Kim","CB","Salzburg"],[5,"M. Jung","CB","Al-Wehda"],[14,"T. Hong","CM","Jeonbuk"],[8,"J. Baek","CM","Jeonbuk"],[16,"K. Hwang","CM","Hangzhou"],[17,"J. Na","RW","Daejeon"],[18,"S. Lee","RW","Gangwon"],[19,"H. Oh","ST","Wolverhampton",1.1],[22,"S. Seol","RW","Reims",1.1],[13,"D. Hong","CM","Ulsan"],
  ]],
  CAN: ["4-3-3", [
    [1,"M. Borjan","GK","Slovan Bratislava"],[2,"A. Johnston","RB","CD Toledo"],[4,"K. Miller","CB","CF Montréal"],[5,"S. Vitória","CB","CF Montréal"],[3,"S. Adekugbe","LB","Hatayspor"],[13,"S. Eustáquio","CDM","FC Porto"],[7,"S. Davies","LB","Bayern Munich",1.2],[6,"I. Koné","CM","Marseille"],[19,"A. Davies","LW","Bayern Munich"],[14,"J. David","ST","Juventus",1.3],[20,"J. Larin","RW","RCD Mallorca",1.1],
    [18,"D. St. Clair","GK","Minnesota Utd"],[12,"D. Crépeau","GK","LAFC"],[15,"M. Kennedy","RB","Celtic"],[26,"M. Bombito","CB","Nice"],[16,"L. Cornelius","LB","Gent"],[8,"L. Fraser","CM","FC Augsburg"],[11,"T. Buchanan","RW","Inter",1.1],[17,"C. Hutchinson","CM","Vancouver"],[9,"C. Larin","ST","Mallorca"],[21,"J. Millar","RW","Hull City"],[10,"J. Hoilett","LW","Aberdeen"],[22,"T. Oluwaseyi","ST","Minnesota Utd",1.1],
  ]],
  ECU: ["4-3-3", [
    [1,"H. Galíndez","GK","Aucas"],[2,"Á. Preciado","RB","Santos Laguna"],[3,"P. Hincapié","CB","Bayer Leverkusen",1.1],[4,"R. Arboleda","CB","São Paulo"],[7,"P. Estupiñán","LB","AC Milan"],[5,"M. Caicedo","CDM","Chelsea",1.2],[13,"J. Ordóñez","CM","Club Brugge"],[8,"A. Franco","CM","Crystal Palace"],[16,"J. Sarmiento","RW","Burnley"],[11,"K. Rodríguez","ST","Spartak Moscow",1.1],[10,"K. Páez","LW","Chelsea",1.2],
    [12,"A. Domínguez","GK","Independiente"],[22,"G. Mina","GK","Aucas"],[17,"Á. Mena","LB","León"],[6,"W. Pacho","CB","Paris SG",1.1],[18,"F. León","CB","LDU Quito"],[14,"C. Gruezo","CDM","San Diego"],[20,"J. Cifuentes","CM","Al-Wakrah"],[23,"M. Caicedo","CM","Independiente"],[9,"E. Valencia","ST","Internacional",1.2],[19,"G. Plata","RW","Flamengo",1.1],[21,"D. Palacios","RW","LDU Quito"],
  ]],
  NGA: ["4-3-3", [
    [23,"S. Nwabali","GK","Chippa United"],[2,"O. Aina","RB","Nottingham Forest"],[5,"C. Bassey","CB","Fulham"],[20,"S. Ajayi","CB","Leicester City"],[3,"J. Sanusi","LB","FC Porto"],[4,"W. Ndidi","CDM","Besiktas"],[8,"F. Onyeka","CM","Brentford"],[18,"A. Iwobi","CM","Fulham"],[11,"A. Lookman","LW","Atalanta",1.3],[9,"V. Osimhen","ST","Galatasaray",1.5],[7,"S. Chukwueze","RW","AC Milan",1.1],
    [1,"S. Okoye","GK","Udinese"],[16,"A. Uzoho","GK","APOEL"],[12,"B. Aina","RB","Nottingham Forest"],[6,"C. Awaziem","CB","Boavista"],[21,"O. Ekong","CB","Al-Kholood"],[15,"M. Sanusi","LB","Hoffenheim"],[14,"R. Aribo","CM","Southampton"],[17,"A. Onyeka","CM","Brentford"],[10,"K. Iheanacho","ST","Sevilla",1.1],[19,"T. Awoniyi","ST","Nottingham Forest",1.1],[13,"M. Dele-Bashiru","CM","Lazio"],[22,"P. Simon","ST","Nantes",1.1],
  ]],
};
