"""init schema

Revision ID: 1592df400e43
Revises: 
Create Date: 2026-06-09 23:17:54.745907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1592df400e43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('pick', sa.String(length=128), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('market', sa.String(length=48), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home', sa.String(length=4), nullable=False),
    sa.Column('away', sa.String(length=4), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('home', sa.String(length=4), nullable=False),
    sa.Column('away', sa.String(length=4), nullable=False),
    sa.Column('group', sa.String(length=2), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=True),
    sa.Column('venue', sa.String(length=96), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ref', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_snapshots_kind'), 'model_snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_model_snapshots_ref'), 'model_snapshots', ['ref'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_key', sa.String(length=64), nullable=False),
    sa.Column('book', sa.String(length=48), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_market_key'), 'odds_snapshots', ['market_key'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pos', sa.String(length=4), nullable=False),
    sa.Column('club', sa.String(length=48), nullable=False),
    sa.Column('tier', sa.Float(), nullable=False),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_code'), 'players', ['code'], unique=False)
    op.create_table('provider_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=96), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('tag', sa.String(length=12), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_news_code'), 'team_news', ['code'], unique=False)
    op.create_table('teams',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=2), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=False),
    sa.Column('defense', sa.Float(), nullable=False),
    sa.Column('str_rating', sa.Float(), nullable=False),
    sa.Column('form', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tournament_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankroll_transactions')
    op.drop_table('tournament_snapshot')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_news_code'), table_name='team_news')
    op.drop_table('team_news')
    op.drop_table('provider_calls')
    op.drop_index(op.f('ix_players_code'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_odds_snapshots_market_key'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_model_snapshots_ref'), table_name='model_snapshots')
    op.drop_index(op.f('ix_model_snapshots_kind'), table_name='model_snapshots')
    op.drop_table('model_snapshots')
    op.drop_table('matches')
    op.drop_table('match_results')
    op.drop_table('bets')
    # ### end Alembic commands ###
