"""
Seed data ported from project/data.js rawTeams, rawMatches, GOALS, NAME, C (colors)
and project/squads.js + project/squads2.js WC_SQUADS.
All 48 teams, 8 marquee matches, full squad lists for all 48 nations.
These are illustrative mock data for WC 2026.
"""
from __future__ import annotations
import math
import random

# ---------------------------------------------------------------------------
# 48 teams — code, group, dec, model, conf, form, str
# ---------------------------------------------------------------------------
TEAMS = [
    # Group A
    {"code": "ARG", "group": "A", "dec": 8.0,    "model": 0.135,  "conf": 81, "form": "WWWWD", "str": 89},
    {"code": "URU", "group": "A", "dec": 29.0,   "model": 0.028,  "conf": 62, "form": "WWDWL", "str": 75},
    {"code": "NGA", "group": "A", "dec": 91.0,   "model": 0.008,  "conf": 46, "form": "LWDWW", "str": 64},
    {"code": "QAT", "group": "A", "dec": 751.0,  "model": 0.0010, "conf": 40, "form": "LWLDL", "str": 52},
    # Group B
    {"code": "ESP", "group": "B", "dec": 5.5,    "model": 0.205,  "conf": 84, "form": "WWWDW", "str": 92},
    {"code": "CRO", "group": "B", "dec": 34.0,   "model": 0.024,  "conf": 60, "form": "DWWDL", "str": 74},
    {"code": "KSA", "group": "B", "dec": 501.0,  "model": 0.0015, "conf": 42, "form": "WLDLW", "str": 55},
    {"code": "UZB", "group": "B", "dec": 751.0,  "model": 0.0010, "conf": 41, "form": "DWLDW", "str": 54},
    # Group C
    {"code": "ENG", "group": "C", "dec": 7.0,    "model": 0.118,  "conf": 74, "form": "WDWLW", "str": 85},
    {"code": "USA", "group": "C", "dec": 26.0,   "model": 0.046,  "conf": 57, "form": "WWDWW", "str": 70},
    {"code": "IRN", "group": "C", "dec": 251.0,  "model": 0.0030, "conf": 55, "form": "WWDLW", "str": 61},
    {"code": "JOR", "group": "C", "dec": 1001.0, "model": 0.0008, "conf": 38, "form": "DLWDL", "str": 50},
    # Group D
    {"code": "BRA", "group": "D", "dec": 7.5,    "model": 0.150,  "conf": 79, "form": "WDWWW", "str": 88},
    {"code": "MAR", "group": "D", "dec": 34.0,   "model": 0.027,  "conf": 61, "form": "WWDWW", "str": 73},
    {"code": "SRB", "group": "D", "dec": 151.0,  "model": 0.0050, "conf": 57, "form": "WLWDL", "str": 68},
    {"code": "NZL", "group": "D", "dec": 1001.0, "model": 0.0008, "conf": 36, "form": "WWLDL", "str": 48},
    # Group E
    {"code": "FRA", "group": "E", "dec": 6.0,    "model": 0.182,  "conf": 82, "form": "WWLWW", "str": 90},
    {"code": "DEN", "group": "E", "dec": 51.0,   "model": 0.015,  "conf": 52, "form": "WLWDW", "str": 69},
    {"code": "AUS", "group": "E", "dec": 301.0,  "model": 0.0020, "conf": 52, "form": "WDWLL", "str": 58},
    {"code": "CRC", "group": "E", "dec": 751.0,  "model": 0.0010, "conf": 41, "form": "LWDLW", "str": 51},
    # Group F
    {"code": "GER", "group": "F", "dec": 11.0,   "model": 0.072,  "conf": 68, "form": "WLWDW", "str": 82},
    {"code": "JPN", "group": "F", "dec": 51.0,   "model": 0.020,  "conf": 56, "form": "WWWDL", "str": 68},
    {"code": "GHA", "group": "F", "dec": 301.0,  "model": 0.0020, "conf": 50, "form": "WLDWL", "str": 60},
    {"code": "PAN", "group": "F", "dec": 751.0,  "model": 0.0010, "conf": 42, "form": "WDLWL", "str": 52},
    # Group G
    {"code": "POR", "group": "G", "dec": 13.0,   "model": 0.071,  "conf": 70, "form": "WWDLW", "str": 83},
    {"code": "MEX", "group": "G", "dec": 41.0,   "model": 0.018,  "conf": 54, "form": "WDLWD", "str": 66},
    {"code": "EGY", "group": "G", "dec": 151.0,  "model": 0.0050, "conf": 56, "form": "WWDWL", "str": 66},
    {"code": "JAM", "group": "G", "dec": 751.0,  "model": 0.0010, "conf": 43, "form": "LWDLW", "str": 53},
    # Group H
    {"code": "NED", "group": "H", "dec": 15.0,   "model": 0.058,  "conf": 66, "form": "DWWLW", "str": 80},
    {"code": "SEN", "group": "H", "dec": 67.0,   "model": 0.012,  "conf": 50, "form": "WDWLD", "str": 67},
    {"code": "CIV", "group": "H", "dec": 151.0,  "model": 0.0050, "conf": 56, "form": "WWLWD", "str": 65},
    {"code": "PAR", "group": "H", "dec": 251.0,  "model": 0.0030, "conf": 50, "form": "DWDLW", "str": 57},
    # Group I
    {"code": "ITA", "group": "I", "dec": 23.0,   "model": 0.034,  "conf": 59, "form": "WDWWL", "str": 78},
    {"code": "BEL", "group": "I", "dec": 26.0,   "model": 0.030,  "conf": 58, "form": "WLDWL", "str": 76},
    {"code": "TUN", "group": "I", "dec": 301.0,  "model": 0.0020, "conf": 50, "form": "WDLDW", "str": 59},
    {"code": "VEN", "group": "I", "dec": 301.0,  "model": 0.0020, "conf": 48, "form": "DWLDW", "str": 56},
    # Group J
    {"code": "COL", "group": "J", "dec": 41.0,   "model": 0.017,  "conf": 53, "form": "DWDWW", "str": 71},
    {"code": "SUI", "group": "J", "dec": 81.0,   "model": 0.009,  "conf": 47, "form": "DLWDW", "str": 65},
    {"code": "UKR", "group": "J", "dec": 201.0,  "model": 0.0040, "conf": 57, "form": "WLWDW", "str": 67},
    {"code": "IRQ", "group": "J", "dec": 751.0,  "model": 0.0010, "conf": 42, "form": "DLWDL", "str": 53},
    # Group K
    {"code": "AUT", "group": "K", "dec": 67.0,   "model": 0.012,  "conf": 60, "form": "WWDWL", "str": 70},
    {"code": "KOR", "group": "K", "dec": 81.0,   "model": 0.010,  "conf": 48, "form": "WDLWW", "str": 62},
    {"code": "CMR", "group": "K", "dec": 251.0,  "model": 0.0030, "conf": 54, "form": "WLWDL", "str": 63},
    {"code": "CAN", "group": "K", "dec": 101.0,  "model": 0.007,  "conf": 44, "form": "WLDWL", "str": 60},
    # Group L
    {"code": "NOR", "group": "L", "dec": 81.0,   "model": 0.010,  "conf": 61, "form": "WWWDL", "str": 71},
    {"code": "TUR", "group": "L", "dec": 151.0,  "model": 0.0050, "conf": 60, "form": "WDWWL", "str": 69},
    {"code": "ALG", "group": "L", "dec": 201.0,  "model": 0.0040, "conf": 56, "form": "WWDWL", "str": 64},
    {"code": "ECU", "group": "L", "dec": 67.0,   "model": 0.011,  "conf": 49, "form": "DWDLW", "str": 63},
]

# ---------------------------------------------------------------------------
# 8 marquee group-stage matches
# ---------------------------------------------------------------------------
MATCHES = [
    {"id": "m1", "home": "ESP", "away": "CRO", "group": "B", "day": "Jun 13", "time": "18:00",
     "venue": "Mercedes-Benz Stadium · Atlanta", "odds": [1.62, 4.0, 5.8], "conf": 78},
    {"id": "m2", "home": "ARG", "away": "NGA", "group": "A", "day": "Jun 13", "time": "21:00",
     "venue": "Estadio Azteca · Mexico City", "odds": [1.40, 4.6, 8.5], "conf": 81},
    {"id": "m3", "home": "ENG", "away": "USA", "group": "C", "day": "Jun 14", "time": "15:00",
     "venue": "MetLife Stadium · New York", "odds": [1.78, 3.7, 4.8], "conf": 64},
    {"id": "m4", "home": "BRA", "away": "MAR", "group": "D", "day": "Jun 14", "time": "18:00",
     "venue": "SoFi Stadium · Los Angeles", "odds": [1.55, 4.1, 6.2], "conf": 71},
    {"id": "m5", "home": "FRA", "away": "DEN", "group": "E", "day": "Jun 15", "time": "21:00",
     "venue": "Lumen Field · Seattle", "odds": [1.50, 4.2, 6.8], "conf": 76},
    {"id": "m6", "home": "GER", "away": "JPN", "group": "F", "day": "Jun 15", "time": "18:00",
     "venue": "Lincoln Financial Field · Philadelphia", "odds": [1.72, 3.9, 5.0], "conf": 63},
    {"id": "m7", "home": "POR", "away": "MEX", "group": "G", "day": "Jun 16", "time": "21:00",
     "venue": "AT&T Stadium · Dallas", "odds": [1.68, 3.8, 5.4], "conf": 69},
    {"id": "m8", "home": "NED", "away": "SEN", "group": "H", "day": "Jun 16", "time": "15:00",
     "venue": "BMO Field · Toronto", "odds": [1.70, 3.8, 5.2], "conf": 60},
]

# ---------------------------------------------------------------------------
# Expected goals per fixture [home xG, away xG]  — from match-extra.js
# ---------------------------------------------------------------------------
GOALS = {
    "m1": [1.9, 0.8],
    "m2": [2.2, 0.6],
    "m3": [1.4, 1.2],
    "m4": [1.7, 0.9],
    "m5": [2.0, 0.7],
    "m6": [1.5, 1.1],
    "m7": [1.8, 0.8],
    "m8": [1.6, 1.0],
}

# ---------------------------------------------------------------------------
# Full name map — all 48 teams
# ---------------------------------------------------------------------------
NAMES = {
    "ESP": "Spain",        "FRA": "France",       "BRA": "Brazil",       "ARG": "Argentina",
    "ENG": "England",      "GER": "Germany",      "POR": "Portugal",     "NED": "Netherlands",
    "BEL": "Belgium",      "ITA": "Italy",        "CRO": "Croatia",      "URU": "Uruguay",
    "COL": "Colombia",     "USA": "USA",           "MEX": "Mexico",       "MAR": "Morocco",
    "JPN": "Japan",        "SEN": "Senegal",       "SUI": "Switzerland",  "DEN": "Denmark",
    "KOR": "South Korea",  "CAN": "Canada",        "ECU": "Ecuador",      "NGA": "Nigeria",
    "QAT": "Qatar",        "KSA": "Saudi Arabia",  "UZB": "Uzbekistan",   "IRN": "Iran",
    "JOR": "Jordan",       "SRB": "Serbia",        "NZL": "New Zealand",  "AUS": "Australia",
    "CRC": "Costa Rica",   "GHA": "Ghana",         "PAN": "Panama",       "EGY": "Egypt",
    "JAM": "Jamaica",      "CIV": "Ivory Coast",   "PAR": "Paraguay",     "TUN": "Tunisia",
    "VEN": "Venezuela",    "UKR": "Ukraine",       "IRQ": "Iraq",         "AUT": "Austria",
    "CMR": "Cameroon",     "NOR": "Norway",        "ALG": "Algeria",      "TUR": "Türkiye",
}

# ---------------------------------------------------------------------------
# Color map — [primary, secondary] for duotone tokens
# ---------------------------------------------------------------------------
COLORS = {
    "ESP": ["#C60B1E", "#FFC400"], "FRA": ["#1F3A93", "#ED2939"],
    "BRA": ["#009C3B", "#FFDF00"], "ARG": ["#6CACE4", "#FFFFFF"],
    "ENG": ["#E1232C", "#1B2A6B"], "GER": ["#111111", "#D00C27"],
    "POR": ["#006600", "#D52B1E"], "NED": ["#FF6A13", "#21468B"],
    "BEL": ["#111111", "#FDDA24"], "ITA": ["#0066A6", "#FFFFFF"],
    "CRO": ["#D6122A", "#1A4B9B"], "URU": ["#55B0E2", "#111111"],
    "COL": ["#FCD116", "#003893"], "USA": ["#1B2A6B", "#E1232C"],
    "MEX": ["#006847", "#CE1126"], "MAR": ["#C1272D", "#006233"],
    "JPN": ["#1A2C6B", "#E60012"], "SEN": ["#00853F", "#FDEF42"],
    "SUI": ["#D52B1E", "#FFFFFF"], "DEN": ["#C8102E", "#FFFFFF"],
    "KOR": ["#13205B", "#CD2E3A"], "CAN": ["#D52B1E", "#FFFFFF"],
    "ECU": ["#FFD100", "#0072CE"], "NGA": ["#008751", "#FFFFFF"],
    "QAT": ["#8A1538", "#FFFFFF"], "KSA": ["#006C35", "#FFFFFF"],
    "UZB": ["#1EB53A", "#0099B5"], "IRN": ["#239F40", "#DA0000"],
    "JOR": ["#111111", "#CE1126"], "SRB": ["#C6363C", "#0C4076"],
    "NZL": ["#111111", "#FFFFFF"], "AUS": ["#00843D", "#FFCD00"],
    "CRC": ["#002B7F", "#CE1126"], "GHA": ["#006B3F", "#FCD116"],
    "PAN": ["#005293", "#DA121A"], "EGY": ["#CE1126", "#1B1B1B"],
    "JAM": ["#009B3A", "#FED100"], "CIV": ["#FF8200", "#009E60"],
    "PAR": ["#0038A8", "#D52B1E"], "TUN": ["#E70013", "#FFFFFF"],
    "VEN": ["#7B1113", "#FCD116"], "UKR": ["#005BBB", "#FFD500"],
    "IRQ": ["#007A3D", "#CE1126"], "AUT": ["#ED2939", "#FFFFFF"],
    "CMR": ["#007A5E", "#CE1126"], "NOR": ["#BA0C2F", "#00205B"],
    "ALG": ["#006233", "#D21034"], "TUR": ["#E30A17", "#FFFFFF"],
}

GROUP_LETTERS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]

# ---------------------------------------------------------------------------
# Full squads from squads.js (24 teams) + squads2.js (24 teams)
# Format: { code: [formation, [[no, name, pos, club, tier?], ...]] }
# First 11 entries per team = projected starting XI
# ---------------------------------------------------------------------------
SQUADS: dict[str, list] = {
    # ---- squads.js (first 24 nations) ------------------------------------
    "ESP": ["4-3-3", [
        [1,"Unai Simón","GK","Athletic Club"],
        [2,"D. Carvajal","RB","Real Madrid"],
        [4,"R. Le Normand","CB","Atlético Madrid"],
        [14,"A. Laporte","CB","Al-Nassr"],
        [24,"M. Cucurella","LB","Chelsea"],
        [16,"Rodri","CDM","Manchester City",1.1],
        [8,"Pedri","CM","Barcelona",1.1],
        [12,"F. Ruiz","CM","Paris SG"],
        [19,"L. Yamal","RW","Barcelona",1.5],
        [7,"Á. Morata","ST","AC Milan",1.3],
        [17,"N. Williams","LW","Athletic Club",1.3],
        [23,"D. Raya","GK","Arsenal"],
        [13,"R. Sánchez","GK","Paris SG"],
        [5,"D. Vivian","CB","Athletic Club"],
        [3,"P. Cubarsí","CB","Barcelona"],
        [22,"J. Navas","RB","Sevilla"],
        [18,"A. Grimaldo","LB","Bayer Leverkusen"],
        [6,"M. Merino","CM","Arsenal"],
        [26,"F. López","CM","Barcelona"],
        [10,"D. Olmo","CAM","Barcelona",1.2],
        [11,"F. Torres","ST","Barcelona",1.1],
        [9,"J. Joselu","ST","Al-Gharafa"],
        [21,"M. Oyarzabal","ST","Real Sociedad",1.1],
        [20,"P. Sarabia","RW","Wolves"],
        [15,"A. Fernández","CB","Real Betis"],
    ]],
    "FRA": ["4-3-3", [
        [1,"M. Maignan","GK","AC Milan"],
        [5,"J. Koundé","RB","Barcelona"],
        [17,"W. Saliba","CB","Arsenal",1.1],
        [4,"D. Upamecano","CB","Bayern Munich"],
        [22,"T. Hernández","LB","AC Milan"],
        [8,"A. Tchouaméni","CDM","Real Madrid"],
        [6,"E. Camavinga","CM","Real Madrid"],
        [7,"A. Griezmann","CAM","Atlético Madrid",1.2],
        [11,"O. Dembélé","RW","Paris SG",1.2],
        [10,"K. Mbappé","ST","Real Madrid",1.6],
        [20,"B. Barcola","LW","Paris SG",1.1],
        [16,"B. Samba","GK","Rennes"],
        [23,"A. Areola","GK","West Ham"],
        [2,"J. Clauss","RB","Nice"],
        [3,"F. Mendy","LB","Real Madrid"],
        [15,"I. Konaté","CB","Liverpool"],
        [24,"L. Hernández","CB","Paris SG"],
        [14,"A. Rabiot","CM","Marseille"],
        [13,"N. Kanté","CDM","Al-Ittihad"],
        [12,"W. Zaïre-Emery","CM","Paris SG"],
        [9,"O. Giroud","ST","Lille",1.1],
        [18,"R. Kolo Muani","ST","Juventus",1.1],
        [26,"M. Thuram","ST","Inter",1.2],
        [21,"K. Coman","RW","Bayern Munich",1.1],
    ]],
    "BRA": ["4-3-3", [
        [1,"Alisson","GK","Liverpool"],
        [2,"Danilo","RB","Flamengo"],
        [4,"Marquinhos","CB","Paris SG"],
        [3,"G. Magalhães","CB","Arsenal"],
        [6,"Wendell","LB","FC Porto"],
        [5,"André","CDM","Wolves"],
        [17,"B. Guimarães","CM","Newcastle"],
        [10,"L. Paquetá","CAM","West Ham",1.1],
        [11,"Rodrygo","RW","Real Madrid",1.2],
        [9,"Endrick","ST","Real Madrid",1.1],
        [20,"Vinícius Jr","LW","Real Madrid",1.5],
        [12,"Bento","GK","Al-Nassr"],
        [23,"Ederson","GK","Manchester City"],
        [13,"Yan Couto","RB","Borussia Dortmund"],
        [14,"É. Militão","CB","Real Madrid"],
        [15,"Beraldo","CB","Paris SG"],
        [16,"Abner","LB","Lyon"],
        [8,"Bruno Guimarães","CM","Newcastle"],
        [18,"Andreas Pereira","CM","Fulham"],
        [7,"Savinho","RW","Manchester City",1.1],
        [19,"Raphinha","LW","Barcelona",1.3],
        [21,"Gabriel Martinelli","LW","Arsenal",1.1],
        [22,"Igor Jesus","ST","Botafogo"],
        [25,"João Pedro","ST","Chelsea",1.1],
    ]],
    "ARG": ["4-3-3", [
        [23,"E. Martínez","GK","Aston Villa"],
        [26,"N. Molina","RB","Atlético Madrid"],
        [13,"C. Romero","CB","Tottenham",1.1],
        [19,"N. Otamendi","CB","Benfica"],
        [3,"N. Tagliafico","LB","Lyon"],
        [7,"R. De Paul","CM","Atlético Madrid"],
        [20,"A. Mac Allister","CM","Liverpool",1.1],
        [24,"E. Fernández","CM","Chelsea"],
        [10,"L. Messi","RW","Inter Miami",1.6],
        [9,"J. Álvarez","ST","Atlético Madrid",1.3],
        [15,"N. González","LW","Juventus",1.1],
        [1,"F. Armani","GK","River Plate"],
        [12,"G. Rulli","GK","Marseille"],
        [2,"G. Montiel","RB","Sevilla"],
        [6,"G. Pezzella","CB","River Plate"],
        [25,"L. Balerdi","CB","Marseille"],
        [8,"M. Acuña","LB","River Plate"],
        [5,"L. Paredes","CDM","Boca Juniors"],
        [18,"G. Lo Celso","CM","Real Betis"],
        [11,"Á. Di María","RW","Benfica",1.1],
        [22,"L. Martínez","ST","Inter",1.3],
        [16,"T. Almada","CAM","Atlético Madrid",1.1],
        [21,"P. Dybala","CAM","Roma",1.1],
        [17,"A. Garnacho","LW","Chelsea",1.1],
    ]],
    "ENG": ["4-2-3-1", [
        [1,"J. Pickford","GK","Everton"],
        [2,"K. Walker","RB","Burnley"],
        [5,"J. Stones","CB","Manchester City"],
        [6,"M. Guéhi","CB","Crystal Palace"],
        [3,"L. Shaw","LB","Manchester Utd"],
        [4,"D. Rice","CDM","Arsenal"],
        [26,"K. Mainoo","CM","Manchester Utd"],
        [7,"B. Saka","RW","Arsenal",1.3],
        [10,"J. Bellingham","CAM","Real Madrid",1.4],
        [11,"P. Foden","LW","Manchester City",1.2],
        [9,"H. Kane","ST","Bayern Munich",1.4],
        [13,"D. Henderson","GK","Brentford"],
        [23,"J. Pope","GK","Newcastle"],
        [12,"K. Trippier","LB","Newcastle"],
        [14,"E. Konsa","CB","Aston Villa"],
        [15,"L. Colwill","CB","Chelsea"],
        [2,"T. Livramento","RB","Newcastle"],
        [8,"A. Wharton","CM","Crystal Palace"],
        [16,"C. Gallagher","CM","Atlético Madrid"],
        [20,"C. Palmer","CAM","Chelsea",1.3],
        [17,"J. Gordon","LW","Newcastle",1.1],
        [19,"O. Watkins","ST","Aston Villa",1.2],
        [24,"M. Rashford","LW","Aston Villa",1.1],
        [21,"E. Eze","CAM","Arsenal",1.1],
    ]],
    "GER": ["4-2-3-1", [
        [1,"M. Neuer","GK","Bayern Munich"],
        [6,"J. Kimmich","RB","Bayern Munich"],
        [4,"J. Tah","CB","Bayern Munich"],
        [2,"A. Rüdiger","CB","Real Madrid",1.1],
        [18,"M. Mittelstädt","LB","VfB Stuttgart"],
        [23,"R. Andrich","CDM","Bayer Leverkusen"],
        [15,"A. Pavlović","CM","Bayern Munich"],
        [19,"L. Sané","RW","Galatasaray",1.1],
        [10,"J. Musiala","CAM","Bayern Munich",1.4],
        [17,"F. Wirtz","LW","Liverpool",1.3],
        [7,"K. Havertz","ST","Arsenal",1.1],
        [12,"O. Baumann","GK","Hoffenheim"],
        [22,"A. Nübel","GK","VfB Stuttgart"],
        [3,"D. Raum","LB","RB Leipzig"],
        [5,"N. Schlotterbeck","CB","Borussia Dortmund"],
        [24,"R. Koch","CB","Eintracht Frankfurt"],
        [16,"W. Anton","CB","Borussia Dortmund"],
        [8,"L. Goretzka","CM","Bayern Munich"],
        [14,"R. Gündoğan","CM","Manchester City",1.1],
        [21,"A. Groß","CM","Borussia Dortmund"],
        [9,"N. Füllkrug","ST","West Ham",1.2],
        [26,"D. Undav","ST","VfB Stuttgart",1.1],
        [11,"K. Adeyemi","RW","Borussia Dortmund",1.1],
        [20,"J. Brandt","CAM","Borussia Dortmund"],
    ]],
    "POR": ["4-3-3", [
        [22,"D. Costa","GK","FC Porto"],
        [20,"J. Cancelo","RB","Al-Hilal"],
        [4,"R. Dias","CB","Manchester City",1.1],
        [24,"A. Inácio","CB","Sporting CP"],
        [19,"N. Mendes","LB","Paris SG"],
        [6,"J. Palhinha","CDM","Bayern Munich"],
        [16,"Vitinha","CM","Paris SG"],
        [8,"B. Fernandes","CAM","Manchester Utd",1.2],
        [11,"B. Silva","RW","Manchester City",1.2],
        [7,"C. Ronaldo","ST","Al-Nassr",1.4],
        [15,"R. Leão","LW","AC Milan",1.3],
        [1,"R. Patrício","GK","free agent"],
        [12,"J. Sá","GK","Wolves"],
        [2,"N. Semedo","RB","Wolves"],
        [3,"Pepe","CB","FC Porto"],
        [5,"Nuno Mendes","LB","Paris SG"],
        [13,"D. Carvalho","CB","Benfica"],
        [14,"G. Inácio","CB","Sporting CP"],
        [18,"R. Neves","CDM","Al-Hilal"],
        [10,"B. Fernandes","CM","Manchester Utd"],
        [23,"V. Ferreira","CM","FC Porto"],
        [9,"G. Ramos","ST","Paris SG",1.2],
        [26,"P. Neto","RW","Chelsea",1.1],
        [17,"F. Conceição","RW","Juventus",1.1],
        [21,"D. Jota","ST","Liverpool",1.2],
    ]],
    "NED": ["4-3-3", [
        [1,"B. Verbruggen","GK","Brighton"],
        [22,"D. Dumfries","RB","Inter"],
        [4,"M. de Ligt","CB","Manchester Utd"],
        [6,"V. van Dijk","CB","Liverpool",1.1],
        [5,"N. Aké","LB","Manchester City"],
        [15,"J. Schouten","CDM","PSV"],
        [21,"F. de Jong","CM","Barcelona",1.2],
        [14,"T. Reijnders","CM","Manchester City"],
        [18,"D. Malen","RW","Aston Villa"],
        [10,"M. Depay","ST","Corinthians",1.2],
        [11,"C. Gakpo","LW","Liverpool",1.2],
        [23,"M. Flekken","GK","Bayer Leverkusen"],
        [13,"N. Bijlow","GK","Feyenoord"],
        [2,"J. Geertruida","RB","RB Leipzig"],
        [3,"M. de Vrij","CB","Inter"],
        [17,"D. Dumfries","RB","Inter"],
        [12,"I. Hartman","LB","Feyenoord"],
        [20,"T. Koopmeiners","CM","Juventus",1.1],
        [8,"M. Wieffer","CM","Brighton"],
        [24,"X. Simons","CAM","RB Leipzig",1.2],
        [7,"X. Simons","RW","RB Leipzig"],
        [9,"W. Weghorst","ST","Ajax",1.1],
        [19,"B. Brobbey","ST","Ajax",1.1],
        [26,"E. Maatsen","LB","Aston Villa"],
    ]],
    "BEL": ["3-4-2-1", [
        [1,"K. Casteels","GK","Al-Qadsiah"],
        [2,"Z. Debast","CB","Sporting CP"],
        [5,"J. Vertonghen","CB","Anderlecht"],
        [3,"A. Theate","CB","Eintracht Frankfurt"],
        [15,"T. Castagne","RWB","Fulham"],
        [6,"A. Onana","CM","Aston Villa"],
        [8,"Y. Tielemans","CM","Aston Villa",1.1],
        [21,"M. De Cuyper","LWB","Brighton"],
        [7,"K. De Bruyne","CAM","Napoli",1.3],
        [10,"L. Trossard","CAM","Arsenal",1.2],
        [9,"R. Lukaku","ST","Napoli",1.3],
        [12,"M. Sels","GK","Nottingham Forest"],
        [13,"T. Kaminski","GK","Metz"],
        [4,"W. Faes","CB","Leicester City"],
        [24,"K. Sardella","RWB","Anderlecht"],
        [18,"O. Mangala","CM","Lyon"],
        [20,"M. Mangala","CM","Everton"],
        [25,"N. Raskin","CM","Rangers"],
        [11,"C. Doku","RW","Manchester City",1.2],
        [22,"J. Bakayoko","RW","PSV",1.1],
        [17,"D. Openda","ST","RB Leipzig",1.2],
        [19,"R. Lukebakio","RW","Sevilla",1.1],
        [14,"D. Vanaken","CM","Club Brugge"],
    ]],
    "CRO": ["4-3-3", [
        [1,"D. Livaković","GK","Fenerbahçe"],
        [2,"J. Stanišić","RB","Bayer Leverkusen"],
        [5,"M. Erlić","CB","Sassuolo"],
        [20,"J. Gvardiol","CB","Manchester City",1.2],
        [19,"B. Sosa","LB","Ajax"],
        [10,"L. Modrić","CM","AC Milan",1.2],
        [8,"M. Kovačić","CM","Manchester City"],
        [26,"L. Sučić","CAM","RB Salzburg"],
        [11,"M. Baturina","RW","RB Leipzig"],
        [9,"A. Kramarić","ST","Hoffenheim",1.1],
        [4,"I. Perišić","LW","Hajduk Split",1.1],
        [12,"I. Nevistić","GK","Dinamo Zagreb"],
        [23,"D. Labrović","GK","Rijeka"],
        [3,"M. Pongračić","CB","Fiorentina"],
        [6,"J. Šutalo","CB","Ajax"],
        [22,"J. Juranović","RB","Union Berlin"],
        [18,"M. Pjaca","LW","Rijeka"],
        [7,"L. Majer","CM","Wolves"],
        [15,"M. Pašalić","CAM","Atalanta",1.1],
        [14,"I. Sunjić","CDM","Spartak Moscow"],
        [17,"A. Budimir","ST","Osasuna",1.1],
        [16,"M. Petković","ST","Dinamo Zagreb"],
        [13,"N. Moro","CM","Hajduk Split"],
    ]],
    "URU": ["4-3-3", [
        [23,"S. Rochet","GK","Inter Miami"],
        [2,"N. Nández","RB","Al-Qadsiah"],
        [19,"S. Coates","CB","Sporting CP"],
        [3,"R. Araújo","CB","Barcelona",1.1],
        [4,"M. Olivera","LB","Napoli"],
        [6,"R. Bentancur","CM","Tottenham"],
        [15,"F. Valverde","CM","Real Madrid",1.3],
        [5,"M. Ugarte","CDM","Manchester Utd"],
        [11,"F. Pellistri","RW","Panathinaikos"],
        [9,"D. Núñez","ST","Liverpool",1.2],
        [7,"N. de la Cruz","LW","Flamengo",1.1],
        [1,"F. Muslera","GK","Galatasaray"],
        [12,"R. Mejía","GK","Liga de Quito"],
        [17,"M. Viña","LB","Flamengo"],
        [22,"R. Cáceres","CB","free agent"],
        [13,"G. Varela","RB","Flamengo"],
        [8,"N. Fonseca","CM","River Plate"],
        [14,"L. Sanabria","CM","Talleres"],
        [10,"G. de Arrascaeta","CAM","Flamengo",1.2],
        [20,"M. Araújo","RW","Juventus"],
        [21,"E. Cavani","ST","Boca Juniors",1.1],
        [18,"M. Satriano","ST","Lens",1.1],
    ]],
    "USA": ["4-3-3", [
        [1,"M. Turner","GK","New England"],
        [2,"S. Dest","RB","PSV"],
        [3,"C. Richards","CB","Crystal Palace"],
        [12,"M. Robinson","CB","Toronto FC"],
        [5,"A. Robinson","LB","Fulham"],
        [4,"T. Adams","CDM","Bournemouth"],
        [8,"W. McKennie","CM","Juventus"],
        [6,"Y. Musah","CM","Atalanta"],
        [10,"C. Pulisic","RW","AC Milan",1.3],
        [9,"F. Balogun","ST","AS Monaco",1.1],
        [21,"T. Weah","LW","Juventus"],
        [13,"M. Freese","GK","NYCFC"],
        [18,"P. Schulte","GK","St. Louis City"],
        [22,"J. Scally","RB","M'gladbach"],
        [15,"C. Carter-Vickers","CB","Celtic"],
        [20,"T. Ream","CB","Charlotte FC"],
        [14,"L. de la Torre","CM","San Diego"],
        [16,"J. Cardoso","CDM","Real Betis"],
        [24,"G. Reyna","CAM","Borussia Dortmund",1.1],
        [11,"B. Aaronson","RW","Leeds Utd"],
        [7,"T. Tillman","CAM","Bayer Leverkusen"],
        [19,"H. Wright","ST","Coventry City"],
        [17,"M. Sargent","ST","Norwich City",1.1],
    ]],
    "COL": ["4-3-3", [
        [1,"C. Vargas","GK","Atlético Mineiro"],
        [4,"S. Arias","RB","Fortaleza"],
        [2,"D. Sánchez","CB","Galatasaray"],
        [3,"J. Lucumí","CB","Bologna"],
        [17,"J. Mojica","LB","Cagliari"],
        [5,"K. Castaño","CDM","Lazio"],
        [16,"J. Lerma","CM","Crystal Palace"],
        [10,"J. Rodríguez","CAM","León",1.2],
        [11,"J. Cuadrado","RW","Pescara"],
        [9,"J. Córdoba","ST","Krasnodar",1.1],
        [7,"L. Díaz","LW","Bayern Munich",1.3],
        [12,"C. Montero","GK","Vélez"],
        [22,"D. Ospina","GK","Atlético Nacional"],
        [13,"Y. Mina","CB","Cagliari"],
        [6,"W. Tesillo","CB","León"],
        [23,"D. Muñoz","RB","Crystal Palace"],
        [8,"R. Ríos","CM","Benfica"],
        [15,"M. Uribe","CM","Atlético Nacional"],
        [14,"L. Sinisterra","RW","Bournemouth",1.1],
        [21,"D. Arias","RW","Atlético Nacional"],
        [19,"R. Borré","ST","Internacional",1.1],
        [18,"J. Borja","ST","River Plate"],
    ]],
    "ITA": ["3-5-2", [
        [1,"G. Donnarumma","GK","Manchester City"],
        [3,"A. Bastoni","CB","Inter"],
        [23,"A. Buongiorno","CB","Napoli"],
        [15,"G. Mancini","CB","Roma"],
        [2,"G. Di Lorenzo","RWB","Napoli"],
        [18,"N. Barella","CM","Inter",1.1],
        [8,"S. Tonali","CM","Newcastle"],
        [10,"L. Pellegrini","CAM","Roma",1.1],
        [13,"F. Dimarco","LWB","Inter"],
        [9,"M. Retegui","ST","Al-Qadsiah",1.2],
        [14,"M. Kean","ST","Fiorentina",1.1],
        [12,"M. Vicario","GK","Tottenham"],
        [22,"G. Vicario","GK","Tottenham"],
        [4,"A. Cambiaso","RWB","Juventus"],
        [5,"R. Calafiori","CB","Arsenal"],
        [6,"G. Scalvini","CB","Atalanta"],
        [16,"D. Frattesi","CM","Inter",1.1],
        [7,"D. Frattesi","CM","Inter"],
        [20,"G. Raspadori","ST","Napoli",1.1],
        [11,"G. Scamacca","ST","Atalanta",1.1],
        [17,"M. Zaccagni","LW","Lazio",1.1],
        [21,"N. Fagioli","CM","Fiorentina"],
        [19,"W. N'Dicka","CB","Roma"],
    ]],
    "SUI": ["4-2-3-1", [
        [1,"Y. Sommer","GK","Inter"],
        [2,"S. Widmer","RB","Mainz"],
        [5,"M. Akanji","CB","Manchester City",1.1],
        [22,"F. Schär","CB","Newcastle"],
        [13,"R. Rodríguez","LB","Real Betis"],
        [10,"G. Xhaka","CDM","Bayer Leverkusen",1.1],
        [8,"R. Freuler","CM","Bologna"],
        [23,"X. Shaqiri","RW","FC Basel",1.1],
        [15,"D. Zakaria","CAM","AS Monaco"],
        [17,"R. Vargas","LW","AS Monaco",1.1],
        [9,"B. Embolo","ST","AS Monaco",1.2],
        [12,"G. Mvogo","GK","Lorient"],
        [21,"P. Köhn","GK","AS Monaco"],
        [3,"S. Lotomba","RB","Nice"],
        [4,"N. Elvedi","CB","M'gladbach"],
        [20,"E. Comert","CB","Spezia"],
        [6,"D. Sow","CM","Nottingham Forest"],
        [16,"V. Sierro","CM","Toulouse"],
        [14,"M. Aebischer","CM","Bologna"],
        [7,"B. Mehmedi","RW","Antalyaspor"],
        [18,"K. Itten","ST","Grasshopper"],
        [11,"Z. Amdouni","ST","Burnley",1.1],
        [19,"D. Ndoye","RW","Bologna",1.1],
    ]],
    "DEN": ["4-3-3", [
        [1,"K. Schmeichel","GK","Celtic"],
        [2,"A. Bah","RB","Benfica"],
        [6,"A. Christensen","CB","Barcelona"],
        [3,"J. Vestergaard","CB","Leicester City"],
        [5,"J. Maehle","LB","Wolfsburg"],
        [23,"P. Højbjerg","CDM","Marseille"],
        [7,"M. Hjulmand","CM","Sporting CP"],
        [10,"C. Eriksen","CAM","Manchester Utd",1.2],
        [8,"M. Damsgaard","RW","Brentford"],
        [9,"R. Højlund","ST","Napoli",1.2],
        [17,"G. Isaksen","LW","Lazio"],
        [16,"M. Ronnow","GK","Union Berlin"],
        [22,"O. Christensen","GK","Hertha Berlin"],
        [4,"J. Andersen","CB","Crystal Palace"],
        [13,"R. Kristensen","RB","Eintracht Frankfurt"],
        [14,"M. Wind","ST","Wolfsburg",1.1],
        [15,"C. Norgaard","CDM","Arsenal"],
        [19,"J. Lindstrom","CAM","Everton",1.1],
        [20,"Y. Poulsen","ST","RB Leipzig",1.1],
        [11,"A. Skov Olsen","RW","Club Brugge",1.1],
        [18,"M. Frese","RB","Hoffenheim"],
        [21,"M. Dorgu","LB","Manchester Utd"],
    ]],
    "MEX": ["4-3-3", [
        [1,"L. Malagón","GK","Club América"],
        [19,"J. Vásquez","RB","Genoa"],
        [3,"C. Montes","CB","Monterrey"],
        [5,"J. Sánchez","CB","Cruz Azul"],
        [23,"J. Gallardo","LB","Tigres"],
        [4,"E. Álvarez","CDM","West Ham",1.1],
        [14,"L. Chávez","CM","Bournemouth"],
        [18,"L. Romo","CM","Monterrey"],
        [22,"H. Lozano","RW","San Diego",1.2],
        [11,"S. Giménez","ST","AC Milan",1.2],
        [7,"U. Antuna","LW","Cruz Azul"],
        [12,"R. Acevedo","GK","Cruz Azul"],
        [13,"C. Acevedo","GK","Santos Laguna"],
        [2,"K. Álvarez","RB","Feyenoord"],
        [15,"I. Vázquez","CB","Toluca"],
        [20,"H. Sánchez","CB","Cruz Azul"],
        [6,"G. Sepúlveda","CDM","Guadalajara"],
        [8,"C. Rodríguez","CM","Club América"],
        [16,"H. Herrera","CM","Houston Dynamo"],
        [10,"A. Vega","CAM","Guadalajara",1.1],
        [9,"R. Jiménez","ST","Fulham",1.2],
        [21,"H. Lozano","RW","San Diego"],
        [17,"O. Pineda","RW","AZ Alkmaar"],
    ]],
    "MAR": ["4-3-3", [
        [1,"Y. Bounou","GK","Al-Hilal"],
        [2,"A. Hakimi","RB","Paris SG",1.2],
        [6,"N. Aguerd","CB","West Ham"],
        [5,"R. Saïss","CB","Al-Shabab"],
        [3,"N. Mazraoui","LB","Manchester Utd"],
        [4,"S. Amrabat","CDM","Fenerbahçe"],
        [8,"A. Ounahi","CM","Panathinaikos"],
        [11,"S. Amallah","CM","Standard Liège"],
        [7,"H. Ziyech","RW","Al-Duhail",1.1],
        [19,"Y. En-Nesyri","ST","Fenerbahçe",1.1],
        [9,"S. Boufal","LW","Al-Rayyan"],
        [12,"M. Aithamou","GK","Le Havre"],
        [22,"A. Tagnaouti","GK","RS Berkane"],
        [18,"A. Hakimi","RB","Paris SG"],
        [20,"A. Masina","LB","Lecce"],
        [24,"J. El Yamiq","CB","Real Valladolid"],
        [14,"Z. Aboukhlal","RW","Toulouse",1.1],
        [15,"S. Ezzalzouli","LW","Real Betis",1.1],
        [17,"S. Ounahi","CM","Marseille"],
        [10,"A. Harit","CAM","Marseille",1.1],
        [21,"W. Cheddira","ST","Espanyol"],
        [16,"A. El Khannouss","CAM","Leicester City",1.1],
    ]],
    "JPN": ["4-2-3-1", [
        [1,"D. Schmidt","GK","Sint-Truiden"],
        [2,"Y. Sugawara","RB","Southampton"],
        [22,"K. Itakura","CB","Ajax"],
        [16,"T. Tomiyasu","CB","Arsenal",1.1],
        [3,"H. Itō","LB","Bayern Munich"],
        [6,"W. Endō","CDM","Liverpool"],
        [7,"H. Morita","CM","Sporting CP"],
        [20,"T. Kubo","RW","Real Sociedad",1.2],
        [15,"D. Kamada","CAM","Crystal Palace"],
        [14,"K. Mitoma","LW","Brighton",1.2],
        [19,"A. Ueda","ST","Feyenoord",1.1],
        [12,"K. Osako","GK","Sanfrecce Hiroshima"],
        [23,"Z. Suzuki","GK","Parma"],
        [4,"K. Taniguchi","CB","Sint-Truiden"],
        [5,"Y. Itakura","CB","Ajax"],
        [26,"H. Sakai","RB","Urawa Reds"],
        [8,"R. Doan","RW","Freiburg",1.1],
        [10,"T. Minamino","CAM","AS Monaco",1.1],
        [13,"H. Morishita","CM","Sanfrecce Hiroshima"],
        [17,"A. Tanaka","CM","Leeds Utd"],
        [9,"K. Ueda","ST","Feyenoord"],
        [11,"K. Furuhashi","ST","Birmingham City",1.1],
        [18,"T. Asano","ST","Partizan"],
    ]],
    "SEN": ["4-3-3", [
        [1,"É. Mendy","GK","Al-Ahli"],
        [21,"Y. Sabaly","RB","Real Betis"],
        [3,"K. Koulibaly","CB","Al-Hilal",1.1],
        [22,"A. Diallo","CB","Al-Arabi"],
        [12,"F. Jakobs","LB","Galatasaray"],
        [5,"P. Gueye","CDM","Villarreal"],
        [17,"P. M. Sarr","CM","Tottenham"],
        [6,"N. Mendy","CM","Al-Ahli"],
        [18,"I. Sarr","RW","Crystal Palace",1.1],
        [9,"N. Jackson","ST","Bayern Munich",1.2],
        [10,"S. Mané","LW","Al-Nassr",1.3],
        [16,"M. Diaw","GK","RS Berkane"],
        [23,"S. Dieng","GK","Le Havre"],
        [2,"K. Mbaye","RB","Bologna"],
        [4,"M. Niakhaté","CB","Lyon"],
        [13,"I. Jakobs","LB","Galatasaray"],
        [8,"L. Camara","CM","RB Salzburg"],
        [15,"K. Kouyaté","CDM","Steaua"],
        [14,"I. Gueye","CM","Everton"],
        [7,"S. Sarr","RW","Standard Liège"],
        [19,"F. Balde","ST","Celta Vigo",1.1],
        [11,"H. Diallo","ST","Al-Ettifaq",1.1],
        [20,"B. Dia","ST","Lazio",1.1],
    ]],
    "KOR": ["4-2-3-1", [
        [1,"S. Kim","GK","Jeonbuk"],
        [2,"Y. Kim","RB","Mainz"],
        [4,"M. Kim","CB","Bayern Munich",1.1],
        [20,"J. Kwon","CB","Hellas Verona"],
        [12,"J. Lee","LB","Paris SG",1.1],
        [6,"I. Hwang","CDM","Genoa"],
        [15,"J. Park","CM","Jeonbuk"],
        [7,"H. Son","RW","LAFC",1.3],
        [10,"K. Lee","CAM","Bayern Munich",1.2],
        [11,"C. Hwang","LW","Wolves",1.1],
        [9,"G. Cho","ST","Norwich City",1.1],
        [21,"B. Jo","GK","Ulsan"],
        [23,"H. Song","GK","Jeonbuk"],
        [3,"Y. Kim","CB","Salzburg"],
        [5,"M. Jung","CB","Al-Wehda"],
        [14,"T. Hong","CM","Jeonbuk"],
        [8,"J. Baek","CM","Jeonbuk"],
        [16,"K. Hwang","CM","Hangzhou"],
        [17,"J. Na","RW","Daejeon"],
        [18,"S. Lee","RW","Gangwon"],
        [19,"H. Oh","ST","Wolverhampton",1.1],
        [22,"S. Seol","RW","Reims",1.1],
        [13,"D. Hong","CM","Ulsan"],
    ]],
    "CAN": ["4-3-3", [
        [1,"M. Borjan","GK","Slovan Bratislava"],
        [2,"A. Johnston","RB","CD Toledo"],
        [4,"K. Miller","CB","CF Montréal"],
        [5,"S. Vitória","CB","CF Montréal"],
        [3,"S. Adekugbe","LB","Hatayspor"],
        [13,"S. Eustáquio","CDM","FC Porto"],
        [7,"S. Davies","LB","Bayern Munich",1.2],
        [6,"I. Koné","CM","Marseille"],
        [19,"A. Davies","LW","Bayern Munich"],
        [14,"J. David","ST","Juventus",1.3],
        [20,"J. Larin","RW","RCD Mallorca",1.1],
        [18,"D. St. Clair","GK","Minnesota Utd"],
        [12,"D. Crépeau","GK","LAFC"],
        [15,"M. Kennedy","RB","Celtic"],
        [26,"M. Bombito","CB","Nice"],
        [16,"L. Cornelius","LB","Gent"],
        [8,"L. Fraser","CM","FC Augsburg"],
        [11,"T. Buchanan","RW","Inter",1.1],
        [17,"C. Hutchinson","CM","Vancouver"],
        [9,"C. Larin","ST","Mallorca"],
        [21,"J. Millar","RW","Hull City"],
        [10,"J. Hoilett","LW","Aberdeen"],
        [22,"T. Oluwaseyi","ST","Minnesota Utd",1.1],
    ]],
    "ECU": ["4-3-3", [
        [1,"H. Galíndez","GK","Aucas"],
        [2,"Á. Preciado","RB","Santos Laguna"],
        [3,"P. Hincapié","CB","Bayer Leverkusen",1.1],
        [4,"R. Arboleda","CB","São Paulo"],
        [7,"P. Estupiñán","LB","AC Milan"],
        [5,"M. Caicedo","CDM","Chelsea",1.2],
        [13,"J. Ordóñez","CM","Club Brugge"],
        [8,"A. Franco","CM","Crystal Palace"],
        [16,"J. Sarmiento","RW","Burnley"],
        [11,"K. Rodríguez","ST","Spartak Moscow",1.1],
        [10,"K. Páez","LW","Chelsea",1.2],
        [12,"A. Domínguez","GK","Independiente"],
        [22,"G. Mina","GK","Aucas"],
        [17,"Á. Mena","LB","León"],
        [6,"W. Pacho","CB","Paris SG",1.1],
        [18,"F. León","CB","LDU Quito"],
        [14,"C. Gruezo","CDM","San Diego"],
        [20,"J. Cifuentes","CM","Al-Wakrah"],
        [23,"M. Caicedo","CM","Independiente"],
        [9,"E. Valencia","ST","Internacional",1.2],
        [19,"G. Plata","RW","Flamengo",1.1],
        [21,"D. Palacios","RW","LDU Quito"],
    ]],
    "NGA": ["4-3-3", [
        [23,"S. Nwabali","GK","Chippa United"],
        [2,"O. Aina","RB","Nottingham Forest"],
        [5,"C. Bassey","CB","Fulham"],
        [20,"S. Ajayi","CB","Leicester City"],
        [3,"J. Sanusi","LB","FC Porto"],
        [4,"W. Ndidi","CDM","Besiktas"],
        [8,"F. Onyeka","CM","Brentford"],
        [18,"A. Iwobi","CM","Fulham"],
        [11,"A. Lookman","LW","Atalanta",1.3],
        [9,"V. Osimhen","ST","Galatasaray",1.5],
        [7,"S. Chukwueze","RW","AC Milan",1.1],
        [1,"S. Okoye","GK","Udinese"],
        [16,"A. Uzoho","GK","APOEL"],
        [12,"B. Aina","RB","Nottingham Forest"],
        [6,"C. Awaziem","CB","Boavista"],
        [21,"O. Ekong","CB","Al-Kholood"],
        [15,"M. Sanusi","LB","Hoffenheim"],
        [14,"R. Aribo","CM","Southampton"],
        [17,"A. Onyeka","CM","Brentford"],
        [10,"K. Iheanacho","ST","Sevilla",1.1],
        [19,"T. Awoniyi","ST","Nottingham Forest",1.1],
        [13,"M. Dele-Bashiru","CM","Lazio"],
        [22,"P. Simon","ST","Nantes",1.1],
    ]],

    # ---- squads2.js (remaining 24 nations) --------------------------------
    "QAT": ["4-3-3", [
        [1,"M. Barsham","GK","Al-Sadd"],
        [2,"Pedro Miguel","RB","Al-Sadd"],
        [15,"B. Khoukhi","CB","Al-Arabi"],
        [4,"T. Salman","CB","Al-Sadd"],
        [3,"A. Hassan","LB","Al-Sadd"],
        [12,"K. Boudiaf","CDM","Al-Duhail"],
        [23,"A. Madibo","CM","Al-Duhail"],
        [10,"H. Al-Haydos","CAM","Al-Sadd"],
        [11,"A. Afif","RW","Al-Sadd",1.3],
        [19,"A. Ali","ST","Al-Duhail",1.2],
        [17,"I. Mohammad","LW","Al-Duhail"],
        [22,"Y. Hassan","GK","Al-Gharafa"],
        [21,"S. Al-Sheeb","GK","Al-Sadd"],
        [5,"B. Al-Rawi","CB","Al-Gharafa"],
        [14,"H. Ahmed","LB","Al-Sadd"],
        [20,"S. Al-Brake","RB","Al-Sadd"],
        [6,"A. Hatim","CM","Al-Sadd"],
        [16,"M. Waad","CB","Al-Rayyan"],
        [8,"M. Muntari","ST","Al-Gharafa",1.1],
        [18,"Kh. Ali","RW","Al-Wakrah"],
        [24,"Y. Abdurisag","LW","Al-Sadd"],
        [25,"A. Alaaeldin","RW","Al-Gharafa"],
        [26,"T. Mohammed","CB","Al-Duhail"],
    ]],
    "KSA": ["4-3-3", [
        [21,"M. Al-Owais","GK","Al-Hilal"],
        [2,"S. Al-Ghannam","RB","Al-Nassr"],
        [3,"A. Al-Bulaihi","CB","Al-Hilal"],
        [5,"H. Tambakti","CB","Al-Hilal"],
        [13,"Y. Al-Shahrani","LB","Al-Hilal"],
        [14,"A. Otayf","CDM","Al-Hilal"],
        [7,"M. Kanno","CM","Al-Hilal"],
        [8,"A. Al-Malki","CM","Al-Ahli"],
        [10,"S. Al-Dawsari","LW","Al-Hilal",1.3],
        [9,"F. Al-Buraikan","ST","Al-Ahli",1.2],
        [11,"S. Al-Shehri","RW","Al-Ittihad",1.1],
        [1,"N. Al-Aqidi","GK","Al-Nassr"],
        [22,"A. Al-Kassar","GK","Al-Riyadh"],
        [4,"A. Madu","CB","Al-Nassr"],
        [6,"S. Abdulhamid","RB","Roma"],
        [15,"A. Al-Amri","CB","Al-Hilal"],
        [16,"N. Al-Dawsari","CM","Al-Nassr"],
        [17,"S. Al-Najei","CM","Al-Nassr"],
        [23,"M. Al-Breik","RB","Al-Hilal"],
        [18,"A. Al-Hamdan","ST","Al-Shabab",1.1],
        [19,"H. Al-Tambakti","CB","Al-Hilal"],
        [20,"F. Al-Ghamdi","RW","Al-Ahli"],
        [12,"A. Al-Aboud","LM","Al-Nassr"],
    ]],
    "UZB": ["4-3-3", [
        [1,"U. Yusupov","GK","Pakhtakor"],
        [4,"A. Khusanov","CB","Manchester City",1.1],
        [3,"R. Ashurmatov","CB","Gangwon"],
        [2,"F. Sayfiev","RB","Pakhtakor"],
        [5,"S. Nasrullaev","LB","Nasaf"],
        [6,"O. Shukurov","CDM","Arsenal Tula"],
        [8,"J. Masharipov","CAM","Pakhtakor",1.2],
        [7,"A. Fayzullaev","RW","CSKA Moscow",1.2],
        [10,"O. Urunov","LW","Neftchi"],
        [9,"E. Shomurodov","ST","Roma",1.3],
        [11,"A. Turgunboev","RW","Pakhtakor"],
        [12,"A. Nematov","GK","Pakhtakor"],
        [22,"V. Frolov","GK","Navbahor"],
        [13,"A. Khamdamov","CAM","Al-Shorta",1.1],
        [14,"I. Sergeev","ST","Pari NN",1.1],
        [15,"K. Tukhtakhujaev","CB","Pakhtakor"],
        [16,"J. Iskanderov","CM","Persepolis"],
        [17,"D. Ergashev","RM","Pakhtakor"],
        [18,"O. Zoteev","CB","Nasaf"],
        [19,"S. Khamrobekov","CM","Sochi"],
        [20,"A. Yusupov","LB","Bunyodkor"],
        [21,"S. Mullajanov","RB","Pakhtakor"],
    ]],
    "IRN": ["4-3-3", [
        [1,"A. Beiranvand","GK","Tractor"],
        [2,"S. Moharrami","RB","Dinamo Zagreb"],
        [8,"M. Hosseini","CB","Kayserispor"],
        [19,"S. Khalilzadeh","CB","Tractor"],
        [3,"E. Hajsafi","LB","Aluminium"],
        [6,"S. Ezatolahi","CDM","Shabab Al-Ahli"],
        [4,"A. Nourollahi","CM","Shabab Al-Ahli"],
        [7,"A. Jahanbakhsh","RW","Heerenveen",1.2],
        [9,"M. Taremi","ST","Inter",1.4],
        [10,"S. Azmoun","LW","Shabab Al-Ahli",1.3],
        [20,"S. Ghoddos","CAM","Brentford"],
        [12,"P. Niazmand","GK","Sepahan"],
        [22,"H. Hosseini","GK","Esteghlal"],
        [5,"M. Mohammadi","LB","AEK Athens"],
        [13,"A. Aghasi","CB","Esteghlal"],
        [15,"M. Pouraliganji","CB","Persepolis"],
        [14,"S. Sadeghi","CDM","Persepolis"],
        [16,"M. Torabi","RW","Al-Shorta",1.1],
        [17,"A. Gholizadeh","LW","Lech Poznan",1.1],
        [11,"K. Ansarifard","ST","Omonia",1.1],
        [18,"A. Karimi","CM","Bayer Leverkusen"],
        [23,"A. Hosseinzadeh","LW","Esteghlal"],
    ]],
    "JOR": ["4-3-3", [
        [21,"Y. Abulaila","GK","Al-Wehdat"],
        [4,"Y. Al-Arab","CB","Al-Faisaly"],
        [5,"A. Nasib","CB","Al-Hussein"],
        [2,"M. Abu Hashish","RB","Al-Faisaly"],
        [3,"S. Al-Ajalin","LB","Al-Wehdat"],
        [6,"N. Al-Rashdan","CDM","Al-Ahli"],
        [8,"N. Al-Rawabdeh","CM","APOEL"],
        [15,"M. Al-Mardi","CM","Al-Faisaly"],
        [7,"M. Al-Taamari","RW","Montpellier",1.3],
        [9,"A. Olwan","ST","Zakho",1.2],
        [17,"Y. Al-Naimat","LW","Al-Okhdood",1.1],
        [1,"A. Al-Fakhouri","GK","Al-Faisaly"],
        [22,"Y. Abu Layla","GK","Al-Hussein"],
        [12,"I. Haddad","RB","Al-Salt"],
        [13,"A. Haddad","CB","Al-Wehdat"],
        [14,"E. Al-Tamari","LB","Al-Ramtha"],
        [16,"R. Bani Attiah","CM","Al-Wehdat"],
        [10,"M. Daghan","CAM","Al-Faisaly"],
        [11,"M. Abu Zraiq","LW","Al-Hussein",1.1],
        [18,"A. Al-Sayed","RW","Al-Wehdat"],
        [19,"M. Khattab","ST","Al-Hussein"],
        [20,"S. Bani Yaseen","CB","Al-Faisaly"],
    ]],
    "SRB": ["3-4-2-1", [
        [1,"V. Milinković-Savić","GK","Torino"],
        [4,"N. Milenković","CB","Nottingham Forest"],
        [6,"S. Pavlović","CB","Manchester Utd"],
        [3,"M. Veljković","CB","Celta Vigo"],
        [22,"A. Živković","RWB","PAOK"],
        [21,"N. Gudelj","CM","Sevilla"],
        [20,"S. Lukić","CM","Fulham"],
        [11,"F. Kostić","LWB","Juventus"],
        [10,"D. Tadić","CAM","Al-Wahda",1.2],
        [8,"S. Milinković-Savić","CAM","Al-Hilal",1.2],
        [9,"A. Mitrović","ST","Al-Hilal",1.3],
        [12,"P. Rajković","GK","Mallorca"],
        [23,"Đ. Petrović","GK","Bournemouth"],
        [5,"S. Eraković","CB","Rangers"],
        [15,"S. Babić","CB","Almería"],
        [2,"M. Stojković","RWB","Red Star"],
        [16,"S. Maksimović","CM","Panathinaikos"],
        [17,"I. Ilić","CM","Torino"],
        [18,"L. Samardžić","CAM","Atalanta",1.1],
        [7,"D. Vlahović","ST","Juventus",1.3],
        [14,"L. Jović","ST","AC Milan",1.1],
        [19,"V. Birmančević","RW","Sporting CP"],
    ]],
    "NZL": ["4-3-3", [
        [1,"O. Sail","GK","Auckland City"],
        [2,"T. Bindon","CB","Nottingham Forest"],
        [5,"M. Boxall","CB","Minnesota Utd"],
        [6,"N. Pijnaker","CB","Hibernian"],
        [3,"L. Cacace","LB","Empoli"],
        [8,"J. Bell","CM","Viking"],
        [14,"M. Stamenic","CM","Olympiacos"],
        [10,"M. Garbett","CAM","Vejle"],
        [7,"B. Old","RW","St. Johnstone"],
        [9,"C. Wood","ST","Nottingham Forest",1.3],
        [11,"K. Barbarouses","LW","Sydney FC"],
        [12,"M. Crocombe","GK","Burton Albion"],
        [22,"A. Paulsen","GK","Brøndby"],
        [4,"F. Surman","CB","Portland Timbers"],
        [15,"S. Roux","RB","Macarthur"],
        [16,"T. Payne","RB","Wellington"],
        [17,"A. Rufer","CDM","Wellington"],
        [13,"M. Bevan","CM","Western Sydney"],
        [18,"S. Singh","CAM","Munich 1860",1.1],
        [19,"E. Just","RW","Vejle",1.1],
        [20,"B. Waine","ST","Shrewsbury"],
        [21,"C. Lewis","LB","Auckland City"],
    ]],
    "AUS": ["4-3-3", [
        [1,"M. Ryan","GK","Roma"],
        [2,"N. Atkinson","RB","Hearts"],
        [19,"H. Souttar","CB","Sheffield Utd"],
        [4,"K. Rowles","CB","Hearts"],
        [16,"A. Behich","LB","Melbourne City"],
        [13,"A. O'Neill","CDM","Go Ahead Eagles"],
        [22,"J. Irvine","CM","St. Pauli",1.1],
        [8,"C. Metcalfe","CM","St. Pauli"],
        [7,"M. Leckie","RW","Melbourne City"],
        [9,"M. Duke","ST","Machida Zelvia",1.1],
        [10,"C. Goodwin","LW","Adelaide Utd",1.1],
        [18,"J. Gauci","GK","Aston Villa"],
        [12,"L. Thomas","GK","Melbourne Victory"],
        [3,"L. Miller","RB","Hibernian"],
        [5,"C. Burgess","CB","Ipswich Town"],
        [20,"T. Deng","CB","Albirex Niigata"],
        [15,"R. McGree","CAM","Middlesbrough"],
        [6,"K. Baccus","CM","Macarthur"],
        [23,"A. Hrustic","CM","Heracles"],
        [11,"K. Yengi","ST","Portsmouth",1.1],
        [17,"M. Boyle","RW","Hibernian"],
        [21,"S. Silvera","RW","Middlesbrough"],
    ]],
    "CRC": ["4-3-3", [
        [1,"K. Navas","GK","Newell's Old Boys",1.1],
        [16,"C. Martínez","RB","Alajuelense"],
        [4,"K. Waston","CB","Saprissa"],
        [19,"K. Fuller","CB","Wolverhampton"],
        [8,"B. Oviedo","LB","Saprissa"],
        [5,"C. Borges","CDM","Saprissa"],
        [17,"Y. Tejeda","CM","Herediano"],
        [20,"B. Aguilera","CAM","Rosario Central"],
        [10,"J. Campbell","RW","Saprissa",1.2],
        [9,"M. Ugalde","ST","Spartak Moscow",1.2],
        [7,"A. Martínez","LW","New York City"],
        [18,"P. Sequeira","GK","Lugano"],
        [23,"E. Alpízar","GK","Alajuelense"],
        [3,"F. Calvo","CB","Konyaspor"],
        [15,"J. P. Vargas","CB","Millonarios"],
        [2,"J. Mora","LB","Saprissa"],
        [6,"O. Galo","CDM","Herediano"],
        [14,"O. Duarte","CB","Alajuelense"],
        [11,"J. Alcócer","RW","Westerlo",1.1],
        [12,"K. Vargas","ST","Hearts",1.1],
        [21,"A. Contreras","ST","Herediano"],
        [22,"C. Mora","RB","Saprissa"],
    ]],
    "GHA": ["4-3-3", [
        [12,"L. Ati-Zigi","GK","St. Gallen"],
        [2,"T. Lamptey","RB","Brighton"],
        [5,"M. Salisu","CB","AS Monaco"],
        [18,"A. Djiku","CB","Fenerbahçe"],
        [3,"G. Mensah","LB","RC Lens"],
        [5,"E. Owusu","CDM","Lorient"],
        [14,"S. Abdul Samed","CM","RC Lens"],
        [10,"T. Partey","CM","Arsenal",1.2],
        [20,"M. Kudus","RW","Tottenham",1.4],
        [9,"I. Williams","ST","Athletic Club",1.3],
        [7,"K. Sulemana","LW","Southampton",1.2],
        [1,"J. Wollacott","GK","Crawley Town"],
        [22,"B. Nurudeen","GK","Asante Kotoko"],
        [4,"A. Seidu","RB","RC Strasbourg"],
        [15,"D. Amartey","CB","Besiktas"],
        [13,"B. Mensah","LB","Black Stars"],
        [8,"M. Ashimeru","CM","Anderlecht"],
        [6,"E. Lamptey","CDM","Almería"],
        [11,"A. Semenyo","RW","Bournemouth",1.1],
        [19,"E. Nuamah","LW","Lyon",1.1],
        [17,"J. Ayew","ST","Leicester City",1.1],
        [21,"F. Echara","ST","Hearts of Oak"],
    ]],
    "PAN": ["4-3-3", [
        [1,"O. Mosquera","GK","Aris Limassol"],
        [16,"M. Murillo","RB","New York Red Bulls"],
        [5,"J. Córdoba","CB","Krasnodar"],
        [3,"F. Escobar","CB","Atlas"],
        [15,"E. Davis","LB","Differdange"],
        [6,"A. Godoy","CDM","San Jose"],
        [20,"A. Carrasquilla","CM","Houston Dynamo"],
        [8,"C. Martínez","CM","Atlético Nacional"],
        [7,"E. Bárcenas","RW","Mazatlán"],
        [9,"J. Fajardo","ST","Independiente",1.1],
        [19,"I. Díaz","LW","Querétaro",1.2],
        [22,"L. Mejía","GK","Universidad de Chile"],
        [12,"J. Saucedo","GK","Plaza Amador"],
        [2,"C. Blackman","RB","Sporting SM"],
        [4,"A. Andrade","CB","Tractor"],
        [23,"E. Bárcenas","LB","Tauro"],
        [13,"J. Welch","CB","Sporting SM"],
        [14,"C. Harvey","CM","Tauro"],
        [17,"J. Rodríguez","RW","CAI",1.1],
        [18,"C. Waterman","ST","Coquimbo Unido",1.1],
        [10,"E. Bárcenas","CAM","Mazatlán"],
        [21,"A. Murillo","LB","Plaza Amador"],
    ]],
    "EGY": ["4-3-3", [
        [1,"M. El-Shenawy","GK","Al-Ahly"],
        [2,"M. Hany","RB","Al-Ahly"],
        [6,"A. Hegazi","CB","Al-Ittihad"],
        [3,"M. Abdelmonem","CB","Nice"],
        [12,"A. Fattouh","LB","Zamalek"],
        [17,"M. Elneny","CDM","Al-Jazira"],
        [8,"E. Ashour","CM","Al-Ahly"],
        [21,"T. Hamed","CM","Al-Wakrah"],
        [10,"M. Salah","RW","Liverpool",1.5],
        [9,"M. Mohamed","ST","Nantes",1.2],
        [14,"O. Marmoush","LW","Manchester City",1.3],
        [23,"M. Abou Gabal","GK","Al-Ahly"],
        [16,"M. Sobhi","GK","Pyramids"],
        [5,"A. Gabr","CB","Smouha"],
        [13,"O. Kamal","LB","Pyramids"],
        [15,"R. Nabil","RB","Al-Ahly"],
        [7,"Trezeguet","RW","Trabzonspor",1.2],
        [18,"A. El Soliya","CM","Al-Ahly"],
        [11,"M. Sherif","ST","Al-Ahly",1.1],
        [19,"I. Adel","CAM","Zamalek"],
        [20,"M. Shehata","RW","Al-Ahly"],
        [22,"A. Koka","LW","Zamalek"],
    ]],
    "JAM": ["4-3-3", [
        [1,"A. Blake","GK","Philadelphia Union"],
        [2,"D. Lembikisa","RB","Wolverhampton"],
        [5,"E. Pinnock","CB","Brentford"],
        [15,"M. Hector","CB","free agent"],
        [3,"G. Leigh","LB","Hull City"],
        [8,"B. De Cordova-Reid","CM","Leicester City"],
        [6,"J. Latibeaudiere","CDM","Coventry City"],
        [10,"K. Palmer","CAM","Coventry City"],
        [7,"D. Gray","RW","Al-Ettifaq",1.2],
        [9,"M. Antonio","ST","West Ham",1.2],
        [11,"L. Bailey","LW","Aston Villa",1.3],
        [12,"J. Waite","GK","Forest Green"],
        [22,"C. McCammon","GK","Charlotte"],
        [4,"D. Lowe","CB","Houston Dynamo"],
        [16,"A. King","RB","Leyton Orient"],
        [13,"R. Williams","LB","Bristol City"],
        [14,"K. Lawrence","CM","Mazatlán"],
        [17,"D. Gardner","CM","Sheffield Wednesday"],
        [18,"S. Nicholson","ST","Spartak Trnava",1.1],
        [19,"T. Decordova","RW","Cavalier"],
        [20,"R. Russell","LW","St. Louis City"],
        [21,"J. Pierre","ST","Detroit City"],
    ]],
    "CIV": ["4-3-3", [
        [16,"Y. Fofana","GK","Angers"],
        [2,"S. Aurier","RB","free agent"],
        [4,"E. Ndicka","CB","Roma"],
        [22,"O. Kossounou","CB","Atalanta"],
        [3,"G. Konan","LB","Al-Ettifaq"],
        [6,"S. Fofana","CDM","Al-Nassr"],
        [19,"I. Sangaré","CM","Nottingham Forest"],
        [8,"F. Kessié","CM","Al-Ahli",1.2],
        [10,"N. Pépé","RW","Villarreal",1.2],
        [9,"S. Haller","ST","Leganés",1.2],
        [11,"S. Adingra","LW","Sunderland",1.1],
        [1,"B. A. Sangaré","GK","Sevilla"],
        [23,"M. Diakité","GK","ASEC Mimosas"],
        [5,"W. Singo","RB","AS Monaco"],
        [12,"W. Boly","CB","Al-Shabab"],
        [15,"O. Diomandé","CB","Sporting CP"],
        [13,"J. M. Seri","CM","Hull City"],
        [17,"I. Diallo","RW","Amiens"],
        [7,"A. Diallo","RW","Manchester Utd",1.3],
        [20,"C. Kouamé","ST","Fiorentina",1.1],
        [18,"J. Bamba","LW","RC Lens",1.1],
        [14,"M. Cornet","RW","West Ham"],
    ]],
    "PAR": ["4-3-3", [
        [1,"A. Silva","GK","Club Libertad"],
        [4,"G. Velázquez","CB","Club Libertad"],
        [2,"F. Balbuena","CB","Internacional"],
        [3,"O. Alderete","CB","Sunderland"],
        [6,"J. Alonso","LB","Krasnodar"],
        [5,"A. Cubas","CDM","Vancouver"],
        [15,"M. Villasanti","CM","Grêmio"],
        [8,"D. Bobadilla","CM","San Lorenzo"],
        [10,"M. Almirón","RW","Atlanta Utd",1.2],
        [19,"A. Sanabria","ST","Cruzeiro",1.2],
        [11,"J. Enciso","LW","Ipswich Town",1.2],
        [12,"R. Fernández","GK","Bahia"],
        [22,"G. Aguilar","GK","Cerro Porteño"],
        [13,"J. Cáceres","RB","Cerro Porteño"],
        [16,"A. Sández","LB","Boca Juniors"],
        [14,"R. Rojas","RB","Talleres"],
        [17,"R. Sosa","RW","Nottingham Forest",1.1],
        [7,"D. Gómez","CM","Inter Miami",1.1],
        [18,"M. Bareiro","ST","San Lorenzo",1.1],
        [20,"O. Bobadilla","CAM","River Plate"],
        [9,"G. Ávalos","ST","Independiente"],
        [21,"B. Ovelar","RW","Olimpia"],
    ]],
    "TUN": ["4-3-3", [
        [16,"A. Dahmen","GK","Sporting Charleroi"],
        [12,"M. Dräger","RB","FC Augsburg"],
        [3,"M. Talbi","CB","Lorient"],
        [2,"Y. Meriah","CB","Esperance"],
        [20,"A. Abdi","LB","Caen"],
        [15,"A. Laïdouni","CDM","Stade Rennais"],
        [13,"F. Sassi","CM","Al-Arabi"],
        [10,"H. Mejbri","CAM","Burnley",1.2],
        [7,"Y. Msakni","RW","Al-Arabi",1.2],
        [9,"S. Jaziri","ST","Esperance",1.1],
        [11,"N. Sliti","LW","Al-Ettifaq",1.1],
        [1,"M. Hassen","GK","Club Africain"],
        [22,"B. Ben Saïd","GK","US Monastir"],
        [5,"D. Bronn","CB","Salernitana"],
        [6,"W. Kechrida","RB","Hatayspor"],
        [4,"M. Bourhane","CB","Esperance"],
        [8,"E. Skhiri","CM","Eintracht Frankfurt",1.1],
        [14,"A. Ben Slimane","CM","Hannover"],
        [17,"E. Achouri","RW","Copenhagen",1.1],
        [18,"O. Layouni","LW","Servette"],
        [19,"H. Rafia","CAM","Lugano"],
        [21,"S. Mestouri","RB","Le Havre"],
    ]],
    "VEN": ["4-3-3", [
        [1,"R. Romo","GK","Tigre"],
        [4,"J. Aramburu","RB","Real Sociedad"],
        [3,"Y. Osorio","CB","Parma"],
        [2,"N. Ferraresi","CB","São Paulo"],
        [14,"M. Navarro","LB","Talleres"],
        [5,"J. Martínez","CDM","Philadelphia Union"],
        [6,"T. Rincón","CM","Santos"],
        [8,"Y. Herrera","CM","Girona",1.2],
        [7,"J. Savarino","RW","Botafogo",1.2],
        [9,"S. Rondón","ST","Pachuca",1.2],
        [11,"Y. Soteldo","LW","Santos",1.2],
        [12,"J. Graterol","GK","Caracas"],
        [22,"W. Faríñez","GK","Lens"],
        [13,"W. Ángel","CB","Apertura"],
        [15,"A. González","RB","Deportivo Táchira"],
        [16,"C. Cásseres","CM","Toulouse"],
        [17,"D. Pereira","CM","Casa Pia"],
        [10,"E. Soto","CAM","Tigres",1.1],
        [18,"D. Machís","LW","Anorthosis",1.1],
        [19,"E. Bello","RW","Lokomotiv Moscow",1.1],
        [20,"J. Martínez","ST","CF Montréal",1.1],
        [21,"K. Rodríguez","RW","Banfield"],
    ]],
    "UKR": ["4-3-3", [
        [1,"A. Trubin","GK","Benfica"],
        [22,"O. Tymchyk","RB","Dynamo Kyiv"],
        [13,"I. Zabarnyi","CB","Bournemouth",1.1],
        [3,"M. Matviyenko","CB","Shakhtar"],
        [16,"V. Mykolenko","LB","Everton"],
        [5,"T. Stepanenko","CDM","Al-Ittihad"],
        [17,"O. Zinchenko","CM","Arsenal",1.1],
        [10,"H. Sudakov","CAM","Benfica",1.2],
        [7,"V. Tsyhankov","RW","Girona",1.1],
        [9,"A. Dovbyk","ST","Roma",1.3],
        [11,"M. Mudryk","LW","Chelsea",1.2],
        [12,"A. Lunin","GK","Real Madrid"],
        [23,"D. Riznyk","GK","Shakhtar"],
        [2,"Y. Konoplya","RB","Shakhtar"],
        [4,"M. Talovierov","CB","Shakhtar"],
        [6,"T. Yarmolenko","RW","Dynamo Kyiv",1.1],
        [8,"R. Malinovskyi","CAM","Genoa",1.2],
        [14,"M. Shaparenko","CM","Dynamo Kyiv"],
        [18,"O. Zubkov","LW","Trabzonspor",1.1],
        [19,"R. Yaremchuk","ST","Olympiacos",1.1],
        [20,"V. Vanat","ST","Dynamo Kyiv",1.1],
        [21,"O. Brazhko","CM","Dynamo Kyiv"],
    ]],
    "IRQ": ["4-2-3-1", [
        [1,"J. Hassan","GK","Al-Quwa Al-Jawiya"],
        [2,"M. Doski","RB","Duhok"],
        [4,"R. Sulaka","CB","Western Sydney"],
        [5,"A. Hashim","CB","Al-Shorta"],
        [3,"H. Ali","LB","Al-Shorta"],
        [6,"A. Al-Ammari","CDM","Mjällby"],
        [8,"B. Resan","CM","Al-Shorta"],
        [7,"I. Bayesh","RW","Al-Quwa Al-Jawiya"],
        [10,"Z. Iqbal","CAM","Utrecht",1.2],
        [11,"A. Jasim","LW","Al-Zawraa",1.1],
        [9,"A. Hussein","ST","Al-Qadsiah",1.2],
        [12,"A. Basil","GK","Al-Shorta"],
        [22,"F. Talib","GK","Al-Quwa Al-Jawiya"],
        [13,"M. Nadhim","CB","Al-Shorta"],
        [14,"M. Younis","CB","Al-Najaf"],
        [15,"S. Sabah","RB","Al-Karkh"],
        [16,"A. Faez","CM","Al-Shorta"],
        [17,"S. Kareem","RW","Erbil",1.1],
        [18,"M. Ali","ST","Al-Duhail",1.2],
        [19,"A. Al-Hamadi","ST","Ipswich Town",1.1],
        [20,"H. Tahir","LM","Al-Quwa Al-Jawiya"],
        [21,"K. Dawood","CB","Al-Shorta"],
    ]],
    "AUT": ["4-2-3-1", [
        [1,"P. Pentz","GK","Brøndby"],
        [2,"S. Posch","RB","Bologna"],
        [15,"P. Lienhart","CB","Freiburg"],
        [4,"K. Danso","CB","Tottenham"],
        [16,"P. Mwene","LB","Mainz"],
        [6,"N. Seiwald","CDM","RB Leipzig"],
        [8,"K. Laimer","CM","Bayern Munich"],
        [19,"C. Baumgartner","RW","RB Leipzig",1.2],
        [10,"M. Sabitzer","CAM","Borussia Dortmund",1.2],
        [9,"M. Gregoritsch","LW","Freiburg",1.1],
        [7,"M. Arnautović","ST","free agent",1.2],
        [12,"H. Lindner","GK","Union Berlin"],
        [23,"N. Hedl","GK","Rapid Wien"],
        [3,"M. Wöber","CB","Borussia M'gladbach"],
        [5,"G. Trauner","CB","Feyenoord"],
        [17,"F. Wimmer","RW","Wolfsburg",1.1],
        [13,"F. Grillitsch","CM","Hoffenheim"],
        [14,"R. Schmid","CM","Werder Bremen"],
        [20,"K. Schmidt","RB","RB Leipzig"],
        [11,"M. Entrup","ST","Hartberg",1.1],
        [18,"R. Sabitzer","RW","Lustenau"],
        [21,"A. Schöpf","CAM","SCR Altach"],
    ]],
    "CMR": ["4-3-3", [
        [1,"A. Onana","GK","Manchester Utd",1.1],
        [2,"C. Fai","RB","free agent"],
        [4,"C. Wooh","CB","Stade Rennais"],
        [3,"J. Castelletto","CB","Nantes"],
        [14,"N. Tolo","LB","Seattle Sounders"],
        [8,"A. Zambo Anguissa","CDM","Napoli",1.2],
        [18,"M. Hongla","CM","Granada"],
        [6,"C. Baleba","CM","Brighton",1.2],
        [7,"B. Mbeumo","RW","Manchester Utd",1.3],
        [10,"V. Aboubakar","ST","Neftçi",1.2],
        [12,"K. Toko Ekambi","LW","Abha",1.1],
        [16,"D. Epassy","GK","Abha"],
        [23,"F. Ondoa","GK","Sabail"],
        [5,"E. Ebosse","CB","Udinese"],
        [15,"J. Tchamadeu","RB","Stoke City"],
        [13,"O. Mbaizo","RB","Philadelphia Union"],
        [17,"P. Kunde","CM","Olympiacos"],
        [19,"F. Magri","CAM","Toulouse",1.1],
        [20,"G. Nkoudou","LW","Damac",1.1],
        [9,"C. Bassogog","RW","Aris",1.1],
        [11,"S. Magnetti","CM","Antalyaspor"],
        [21,"J. Onana","CDM","Lyon"],
    ]],
    "NOR": ["4-3-3", [
        [12,"Ø. Nyland","GK","Sevilla"],
        [2,"J. Ryerson","RB","Borussia Dortmund"],
        [5,"K. Ajer","CB","Brentford"],
        [6,"L. Østigård","CB","Stade Rennais"],
        [3,"B. Meling","LB","Stade Rennais"],
        [8,"S. Berge","CDM","Fulham"],
        [18,"F. Aursnes","CM","Benfica"],
        [20,"M. Ødegaard","CM","Arsenal",1.3],
        [7,"A. Nusa","RW","RB Leipzig",1.2],
        [9,"E. Haaland","ST","Manchester City",1.6],
        [11,"A. Sørloth","LW","Atlético Madrid",1.3],
        [1,"E. Selvik","GK","Brann"],
        [22,"M. Dyngeland","GK","Brann"],
        [4,"M. Høibråten","CB","Union Berlin"],
        [15,"D. M. Wolfe","LB","Nice"],
        [13,"A. Heggem","CB","Bologna"],
        [16,"P. Berg","CM","Bodø/Glimt"],
        [17,"O. Bobb","RW","Manchester City",1.1],
        [14,"J. Strand Larsen","ST","Wolverhampton",1.2],
        [19,"O. Solbakken","LW","Olympiacos",1.1],
        [10,"K. Thorsby","CM","Genoa"],
        [21,"H. Nordås","CM","Brann"],
    ]],
    "ALG": ["4-3-3", [
        [1,"A. Mandrea","GK","AS Monaco"],
        [2,"Y. Atal","RB","Al-Sadd"],
        [5,"A. Mandi","CB","Lille"],
        [15,"M. Tougai","CB","Espérance"],
        [3,"R. Bensebaïni","LB","Borussia Dortmund",1.1],
        [8,"N. Bentaleb","CDM","Angers"],
        [13,"R. Zerrouki","CM","Feyenoord"],
        [6,"I. Bennacer","CM","AC Milan",1.2],
        [7,"R. Mahrez","RW","Al-Ahli",1.3],
        [9,"B. Bounedjah","ST","Al-Sadd",1.2],
        [11,"A. Gouiri","LW","Marseille",1.2],
        [16,"A. Oukidja","GK","Saint-Étienne"],
        [23,"L. Zidane","GK","Granada"],
        [4,"A. Touba","CB","Trabzonspor"],
        [12,"J. Hadjam","LB","Young Boys"],
        [14,"H. Aouar","CAM","Roma",1.1],
        [17,"A. Ounas","RW","Lille",1.1],
        [18,"M. Amoura","ST","Wolfsburg",1.2],
        [10,"S. Benrahma","LW","Neom",1.1],
        [19,"I. Slimani","ST","Mechelen",1.1],
        [20,"F. Chaïbi","CAM","Eintracht Frankfurt"],
        [21,"H. Boudaoui","CM","Nice"],
    ]],
    "TUR": ["4-2-3-1", [
        [1,"M. Günok","GK","Besiktas"],
        [2,"Z. Çelik","RB","AS Roma"],
        [3,"M. Demiral","CB","Al-Ahli"],
        [4,"A. Bardakcı","CB","Galatasaray"],
        [20,"F. Kadıoğlu","LB","Inter"],
        [8,"S. Özcan","CDM","Borussia Dortmund"],
        [7,"İ. Yüksek","CM","Fenerbahçe"],
        [15,"K. Yıldız","RW","Juventus",1.3],
        [10,"H. Çalhanoğlu","CAM","Inter",1.3],
        [17,"K. Aktürkoğlu","LW","Benfica",1.2],
        [9,"B. A. Yılmaz","ST","Galatasaray",1.1],
        [12,"U. Çakır","GK","Galatasaray"],
        [23,"A. Bayındır","GK","Manchester Utd"],
        [5,"M. Müldür","RB","Sassuolo"],
        [14,"S. Akaydın","CB","Montpellier"],
        [16,"O. Kökçü","CM","Benfica",1.1],
        [6,"O. Ayhan","CDM","Galatasaray"],
        [18,"A. Güler","CAM","Real Madrid",1.3],
        [11,"Y. Yazıcı","RW","Hull City",1.1],
        [19,"C. Tosun","ST","Besiktas",1.1],
        [21,"S. Kılıçsoy","ST","Besiktas",1.1],
        [22,"E. Yıldız","LW","Galatasaray"],
    ]],
}


# ---------------------------------------------------------------------------
# Synthetic history generator — deterministic Poisson-sampled results
# ---------------------------------------------------------------------------

def _pois_sample(rng: random.Random, mu: float) -> int:
    """Sample from Poisson(mu) using Knuth algorithm."""
    L = math.exp(-mu)
    k = 0
    p = 1.0
    while True:
        k += 1
        p *= rng.random()
        if p <= L:
            return k - 1


def synth_history(n_per_team: int = 12, seed: int = 42) -> list[dict]:
    """
    Generate ~n_per_team results per team from str ratings via Poisson so
    ratings.py can be calibrated deterministically without a real API.
    """
    rng = random.Random(seed)
    codes = [t["code"] for t in TEAMS]
    strength = {t["code"]: t["str"] for t in TEAMS}
    out = []
    base = 1.35
    for _ in range(n_per_team * len(codes) // 2):
        h, a = rng.sample(codes, 2)
        lh = base * math.exp((strength[h] - 70) / 40 + 0.15)
        la = base * math.exp((strength[a] - 70) / 40)
        hg = _pois_sample(rng, lh)
        ag = _pois_sample(rng, la)
        out.append({
            "home": h,
            "away": a,
            "home_goals": hg,
            "away_goals": ag,
            "days_ago": rng.randint(20, 900),
        })
    return out
